// This file is generated by imgui-wasm-python/tools/generate_bindings.py.
#![allow(non_snake_case)]
#![allow(unused_imports)]
use std::ffi::c_void;
use std::os::raw::{c_char, c_double, c_int, c_uchar, c_uint, c_ushort};

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ImVec2 {
    pub x: f32,
    pub y: f32,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ImVec4 {
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub w: f32,
}

extern "C" {
    #[link_name = "igAcceptDragDropPayload"]
    fn c_igAcceptDragDropPayload(arg0: *const c_char, arg1: c_int) -> *const c_void;
    #[link_name = "igAlignTextToFramePadding"]
    fn c_igAlignTextToFramePadding() -> ();
    #[link_name = "igArrowButton"]
    fn c_igArrowButton(arg0: *const c_char, arg1: c_int) -> bool;
    #[link_name = "igBegin"]
    fn c_igBegin(arg0: *const c_char, arg1: *mut bool, arg2: c_int) -> bool;
    #[link_name = "igBeginChild"]
    fn c_igBeginChild(arg0: *const c_char, arg1: ImVec2, arg2: c_int, arg3: c_int) -> bool;
    #[link_name = "igBeginChildID"]
    fn c_igBeginChildID(arg0: c_uint, arg1: ImVec2, arg2: c_int, arg3: c_int) -> bool;
    #[link_name = "igBeginCombo"]
    fn c_igBeginCombo(arg0: *const c_char, arg1: *const c_char, arg2: c_int) -> bool;
    #[link_name = "igBeginDisabled"]
    fn c_igBeginDisabled(arg0: bool) -> ();
    #[link_name = "igBeginDragDropSource"]
    fn c_igBeginDragDropSource(arg0: c_int) -> bool;
    #[link_name = "igBeginDragDropTarget"]
    fn c_igBeginDragDropTarget() -> bool;
    #[link_name = "igBeginGroup"]
    fn c_igBeginGroup() -> ();
    #[link_name = "igBeginItemTooltip"]
    fn c_igBeginItemTooltip() -> bool;
    #[link_name = "igBeginListBox"]
    fn c_igBeginListBox(arg0: *const c_char, arg1: ImVec2) -> bool;
    #[link_name = "igBeginMainMenuBar"]
    fn c_igBeginMainMenuBar() -> bool;
    #[link_name = "igBeginMenu"]
    fn c_igBeginMenu(arg0: *const c_char, arg1: bool) -> bool;
    #[link_name = "igBeginMenuBar"]
    fn c_igBeginMenuBar() -> bool;
    #[link_name = "igBeginMultiSelect"]
    fn c_igBeginMultiSelect(arg0: c_int, arg1: c_int, arg2: c_int) -> *mut c_void;
    #[link_name = "igBeginPopup"]
    fn c_igBeginPopup(arg0: *const c_char, arg1: c_int) -> bool;
    #[link_name = "igBeginPopupContextItem"]
    fn c_igBeginPopupContextItem(arg0: *const c_char, arg1: c_int) -> bool;
    #[link_name = "igBeginPopupContextVoid"]
    fn c_igBeginPopupContextVoid(arg0: *const c_char, arg1: c_int) -> bool;
    #[link_name = "igBeginPopupContextWindow"]
    fn c_igBeginPopupContextWindow(arg0: *const c_char, arg1: c_int) -> bool;
    #[link_name = "igBeginPopupModal"]
    fn c_igBeginPopupModal(arg0: *const c_char, arg1: *mut bool, arg2: c_int) -> bool;
    #[link_name = "igBeginTabBar"]
    fn c_igBeginTabBar(arg0: *const c_char, arg1: c_int) -> bool;
    #[link_name = "igBeginTabItem"]
    fn c_igBeginTabItem(arg0: *const c_char, arg1: *mut bool, arg2: c_int) -> bool;
    #[link_name = "igBeginTable"]
    fn c_igBeginTable(arg0: *const c_char, arg1: c_int, arg2: c_int, arg3: ImVec2, arg4: f32) -> bool;
    #[link_name = "igBeginTooltip"]
    fn c_igBeginTooltip() -> bool;
    #[link_name = "igBullet"]
    fn c_igBullet() -> ();
    #[link_name = "igButton"]
    fn c_igButton(arg0: *const c_char, arg1: ImVec2) -> bool;
    #[link_name = "igCalcItemWidth"]
    fn c_igCalcItemWidth() -> f32;
    #[link_name = "igCalcTextSize"]
    fn c_igCalcTextSize(arg0: *const c_char, arg1: *const c_char, arg2: bool, arg3: f32) -> ImVec2;
    #[link_name = "igCheckbox"]
    fn c_igCheckbox(arg0: *const c_char, arg1: *mut bool) -> bool;
    #[link_name = "igCheckboxFlagsIntPtr"]
    fn c_igCheckboxFlagsIntPtr(arg0: *const c_char, arg1: *mut c_int, arg2: c_int) -> bool;
    #[link_name = "igCheckboxFlagsUintPtr"]
    fn c_igCheckboxFlagsUintPtr(arg0: *const c_char, arg1: *mut c_uint, arg2: c_uint) -> bool;
    #[link_name = "igCloseCurrentPopup"]
    fn c_igCloseCurrentPopup() -> ();
    #[link_name = "igCollapsingHeader"]
    fn c_igCollapsingHeader(arg0: *const c_char, arg1: c_int) -> bool;
    #[link_name = "igCollapsingHeaderBoolPtr"]
    fn c_igCollapsingHeaderBoolPtr(arg0: *const c_char, arg1: *mut bool, arg2: c_int) -> bool;
    #[link_name = "igColorButton"]
    fn c_igColorButton(arg0: *const c_char, arg1: ImVec4, arg2: c_int, arg3: ImVec2) -> bool;
    #[link_name = "igColorConvertFloat4ToU32"]
    fn c_igColorConvertFloat4ToU32(arg0: ImVec4) -> u32;
    #[link_name = "igColorConvertHSVtoRGB"]
    fn c_igColorConvertHSVtoRGB(arg0: f32, arg1: f32, arg2: f32, arg3: *mut f32, arg4: *mut f32, arg5: *mut f32) -> ();
    #[link_name = "igColorConvertRGBtoHSV"]
    fn c_igColorConvertRGBtoHSV(arg0: f32, arg1: f32, arg2: f32, arg3: *mut f32, arg4: *mut f32, arg5: *mut f32) -> ();
    #[link_name = "igColorConvertU32ToFloat4"]
    fn c_igColorConvertU32ToFloat4(arg0: u32) -> ImVec4;
    #[link_name = "igColorEdit3"]
    fn c_igColorEdit3(arg0: *const c_char, arg1: *mut f32, arg2: c_int) -> bool;
    #[link_name = "igColorEdit4"]
    fn c_igColorEdit4(arg0: *const c_char, arg1: *mut f32, arg2: c_int) -> bool;
    #[link_name = "igColorPicker3"]
    fn c_igColorPicker3(arg0: *const c_char, arg1: *mut f32, arg2: c_int) -> bool;
    #[link_name = "igColorPicker4"]
    fn c_igColorPicker4(arg0: *const c_char, arg1: *mut f32, arg2: c_int, arg3: *const f32) -> bool;
    #[link_name = "igColumns"]
    fn c_igColumns(arg0: c_int, arg1: *const c_char, arg2: bool) -> ();
    #[link_name = "igCombo"]
    fn c_igCombo(arg0: *const c_char, arg1: *mut c_int, arg2: *const c_char, arg3: c_int) -> bool;
    #[link_name = "igComboChar"]
    fn c_igComboChar(arg0: *const c_char, arg1: *mut c_int, arg2: *const *const c_char, arg3: c_int, arg4: c_int) -> bool;
    #[link_name = "igCreateContext"]
    fn c_igCreateContext(arg0: *mut c_void) -> *mut c_void;
    #[link_name = "igDebugCheckVersionAndDataLayout"]
    fn c_igDebugCheckVersionAndDataLayout(arg0: *const c_char, arg1: usize, arg2: usize, arg3: usize, arg4: usize, arg5: usize, arg6: usize) -> bool;
    #[link_name = "igDebugStartItemPicker"]
    fn c_igDebugStartItemPicker() -> ();
    #[link_name = "igDebugTextEncoding"]
    fn c_igDebugTextEncoding(arg0: *const c_char) -> ();
    #[link_name = "igDestroyContext"]
    fn c_igDestroyContext(arg0: *mut c_void) -> ();
    #[link_name = "igDestroyPlatformWindows"]
    fn c_igDestroyPlatformWindows() -> ();
    #[link_name = "igDockSpace"]
    fn c_igDockSpace(arg0: c_uint, arg1: ImVec2, arg2: c_int, arg3: *const c_void) -> c_uint;
    #[link_name = "igDockSpaceOverViewport"]
    fn c_igDockSpaceOverViewport(arg0: c_uint, arg1: *const c_void, arg2: c_int, arg3: *const c_void) -> c_uint;
    #[link_name = "igDragFloat"]
    fn c_igDragFloat(arg0: *const c_char, arg1: *mut f32, arg2: f32, arg3: f32, arg4: f32, arg5: *const c_char, arg6: c_int) -> bool;
    #[link_name = "igDragFloat3"]
    fn c_igDragFloat3(arg0: *const c_char, arg1: *mut f32, arg2: f32, arg3: f32, arg4: f32, arg5: *const c_char, arg6: c_int) -> bool;
    #[link_name = "igDragFloat4"]
    fn c_igDragFloat4(arg0: *const c_char, arg1: *mut f32, arg2: f32, arg3: f32, arg4: f32, arg5: *const c_char, arg6: c_int) -> bool;
    #[link_name = "igDragFloatRange2"]
    fn c_igDragFloatRange2(arg0: *const c_char, arg1: *mut f32, arg2: *mut f32, arg3: f32, arg4: f32, arg5: f32, arg6: *const c_char, arg7: *const c_char, arg8: c_int) -> bool;
    #[link_name = "igDragInt"]
    fn c_igDragInt(arg0: *const c_char, arg1: *mut c_int, arg2: f32, arg3: c_int, arg4: c_int, arg5: *const c_char, arg6: c_int) -> bool;
    #[link_name = "igDragIntRange2"]
    fn c_igDragIntRange2(arg0: *const c_char, arg1: *mut c_int, arg2: *mut c_int, arg3: f32, arg4: c_int, arg5: c_int, arg6: *const c_char, arg7: *const c_char, arg8: c_int) -> bool;
    #[link_name = "igDummy"]
    fn c_igDummy(arg0: ImVec2) -> ();
    #[link_name = "igEnd"]
    fn c_igEnd() -> ();
    #[link_name = "igEndChild"]
    fn c_igEndChild() -> ();
    #[link_name = "igEndCombo"]
    fn c_igEndCombo() -> ();
    #[link_name = "igEndDisabled"]
    fn c_igEndDisabled() -> ();
    #[link_name = "igEndDragDropSource"]
    fn c_igEndDragDropSource() -> ();
    #[link_name = "igEndDragDropTarget"]
    fn c_igEndDragDropTarget() -> ();
    #[link_name = "igEndFrame"]
    fn c_igEndFrame() -> ();
    #[link_name = "igEndGroup"]
    fn c_igEndGroup() -> ();
    #[link_name = "igEndListBox"]
    fn c_igEndListBox() -> ();
    #[link_name = "igEndMainMenuBar"]
    fn c_igEndMainMenuBar() -> ();
    #[link_name = "igEndMenu"]
    fn c_igEndMenu() -> ();
    #[link_name = "igEndMenuBar"]
    fn c_igEndMenuBar() -> ();
    #[link_name = "igEndMultiSelect"]
    fn c_igEndMultiSelect() -> *mut c_void;
    #[link_name = "igEndPopup"]
    fn c_igEndPopup() -> ();
    #[link_name = "igEndTabBar"]
    fn c_igEndTabBar() -> ();
    #[link_name = "igEndTabItem"]
    fn c_igEndTabItem() -> ();
    #[link_name = "igEndTable"]
    fn c_igEndTable() -> ();
    #[link_name = "igEndTooltip"]
    fn c_igEndTooltip() -> ();
    #[link_name = "igFindViewportByID"]
    fn c_igFindViewportByID(arg0: c_uint) -> *mut c_void;
    #[link_name = "igFindViewportByPlatformHandle"]
    fn c_igFindViewportByPlatformHandle(arg0: *mut c_void) -> *mut c_void;
    #[link_name = "igGetAllocatorFunctions"]
    fn c_igGetAllocatorFunctions(arg0: *mut c_void, arg1: *mut c_void, arg2: *mut *mut c_void) -> ();
    #[link_name = "igGetBackgroundDrawList"]
    fn c_igGetBackgroundDrawList(arg0: *mut c_void) -> *mut c_void;
    #[link_name = "igGetClipboardText"]
    fn c_igGetClipboardText() -> *const c_char;
    #[link_name = "igGetColorU32ImU32"]
    fn c_igGetColorU32ImU32(arg0: u32, arg1: f32) -> u32;
    #[link_name = "igGetColorU32ImVec4"]
    fn c_igGetColorU32ImVec4(arg0: ImVec4) -> u32;
    #[link_name = "igGetColumnIndex"]
    fn c_igGetColumnIndex() -> c_int;
    #[link_name = "igGetColumnOffset"]
    fn c_igGetColumnOffset(arg0: c_int) -> f32;
    #[link_name = "igGetColumnWidth"]
    fn c_igGetColumnWidth(arg0: c_int) -> f32;
    #[link_name = "igGetColumnsCount"]
    fn c_igGetColumnsCount() -> c_int;
    #[link_name = "igGetContentRegionAvail"]
    fn c_igGetContentRegionAvail() -> ImVec2;
    #[link_name = "igGetContentRegionMax"]
    fn c_igGetContentRegionMax() -> ImVec2;
    #[link_name = "igGetCurrentContext"]
    fn c_igGetCurrentContext() -> *mut c_void;
    #[link_name = "igGetCursorPos"]
    fn c_igGetCursorPos() -> ImVec2;
    #[link_name = "igGetCursorPosX"]
    fn c_igGetCursorPosX() -> f32;
    #[link_name = "igGetCursorPosY"]
    fn c_igGetCursorPosY() -> f32;
    #[link_name = "igGetCursorScreenPos"]
    fn c_igGetCursorScreenPos() -> ImVec2;
    #[link_name = "igGetCursorStartPos"]
    fn c_igGetCursorStartPos() -> ImVec2;
    #[link_name = "igGetDragDropPayload"]
    fn c_igGetDragDropPayload() -> *const c_void;
    #[link_name = "igGetDrawData"]
    fn c_igGetDrawData() -> *mut c_void;
    #[link_name = "igGetDrawListSharedData"]
    fn c_igGetDrawListSharedData() -> *mut c_void;
    #[link_name = "igGetFont"]
    fn c_igGetFont() -> *mut c_void;
    #[link_name = "igGetFontBaked"]
    fn c_igGetFontBaked() -> *mut c_void;
    #[link_name = "igGetFontSize"]
    fn c_igGetFontSize() -> f32;
    #[link_name = "igGetFontTexUvWhitePixel"]
    fn c_igGetFontTexUvWhitePixel() -> ImVec2;
    #[link_name = "igGetForegroundDrawList"]
    fn c_igGetForegroundDrawList(arg0: *mut c_void) -> *mut c_void;
    #[link_name = "igGetFrameCount"]
    fn c_igGetFrameCount() -> c_int;
    #[link_name = "igGetFrameHeight"]
    fn c_igGetFrameHeight() -> f32;
    #[link_name = "igGetFrameHeightWithSpacing"]
    fn c_igGetFrameHeightWithSpacing() -> f32;
    #[link_name = "igGetID"]
    fn c_igGetID(arg0: *const c_char) -> c_uint;
    #[link_name = "igGetIDInt"]
    fn c_igGetIDInt(arg0: c_int) -> c_uint;
    #[link_name = "igGetIDPtr"]
    fn c_igGetIDPtr(arg0: *const c_void) -> c_uint;
    #[link_name = "igGetIDStr"]
    fn c_igGetIDStr(arg0: *const c_char, arg1: *const c_char) -> c_uint;
    #[link_name = "igGetIO"]
    fn c_igGetIO() -> *mut c_void;
    #[link_name = "igGetItemFlags"]
    fn c_igGetItemFlags() -> c_int;
    #[link_name = "igGetItemID"]
    fn c_igGetItemID() -> c_uint;
    #[link_name = "igGetItemRectMax"]
    fn c_igGetItemRectMax() -> ImVec2;
    #[link_name = "igGetItemRectMin"]
    fn c_igGetItemRectMin() -> ImVec2;
    #[link_name = "igGetItemRectSize"]
    fn c_igGetItemRectSize() -> ImVec2;
    #[link_name = "igGetKeyName"]
    fn c_igGetKeyName(arg0: c_int) -> *const c_char;
    #[link_name = "igGetKeyPressedAmount"]
    fn c_igGetKeyPressedAmount(arg0: c_int, arg1: f32, arg2: f32) -> c_int;
    #[link_name = "igGetMainViewport"]
    fn c_igGetMainViewport() -> *mut c_void;
    #[link_name = "igGetMouseClickedCount"]
    fn c_igGetMouseClickedCount(arg0: c_int) -> c_int;
    #[link_name = "igGetMouseCursor"]
    fn c_igGetMouseCursor() -> c_int;
    #[link_name = "igGetMouseDragDelta"]
    fn c_igGetMouseDragDelta(arg0: c_int, arg1: f32) -> ImVec2;
    #[link_name = "igGetMousePos"]
    fn c_igGetMousePos() -> ImVec2;
    #[link_name = "igGetMousePosOnOpeningCurrentPopup"]
    fn c_igGetMousePosOnOpeningCurrentPopup() -> ImVec2;
    #[link_name = "igGetPlatformIO"]
    fn c_igGetPlatformIO() -> *mut c_void;
    #[link_name = "igGetScrollMaxX"]
    fn c_igGetScrollMaxX() -> f32;
    #[link_name = "igGetScrollMaxY"]
    fn c_igGetScrollMaxY() -> f32;
    #[link_name = "igGetScrollX"]
    fn c_igGetScrollX() -> f32;
    #[link_name = "igGetScrollY"]
    fn c_igGetScrollY() -> f32;
    #[link_name = "igGetStateStorage"]
    fn c_igGetStateStorage() -> *mut c_void;
    #[link_name = "igGetStyle"]
    fn c_igGetStyle() -> *mut c_void;
    #[link_name = "igGetTextLineHeight"]
    fn c_igGetTextLineHeight() -> f32;
    #[link_name = "igGetTextLineHeightWithSpacing"]
    fn c_igGetTextLineHeightWithSpacing() -> f32;
    #[link_name = "igGetTime"]
    fn c_igGetTime() -> c_double;
    #[link_name = "igGetTreeNodeToLabelSpacing"]
    fn c_igGetTreeNodeToLabelSpacing() -> f32;
    #[link_name = "igGetVersion"]
    fn c_igGetVersion() -> *const c_char;
    #[link_name = "igGetWindowContentRegionMax"]
    fn c_igGetWindowContentRegionMax() -> ImVec2;
    #[link_name = "igGetWindowContentRegionMin"]
    fn c_igGetWindowContentRegionMin() -> ImVec2;
    #[link_name = "igGetWindowDockID"]
    fn c_igGetWindowDockID() -> c_uint;
    #[link_name = "igGetWindowDpiScale"]
    fn c_igGetWindowDpiScale() -> f32;
    #[link_name = "igGetWindowDrawList"]
    fn c_igGetWindowDrawList() -> *mut c_void;
    #[link_name = "igGetWindowHeight"]
    fn c_igGetWindowHeight() -> f32;
    #[link_name = "igGetWindowPos"]
    fn c_igGetWindowPos() -> ImVec2;
    #[link_name = "igGetWindowSize"]
    fn c_igGetWindowSize() -> ImVec2;
    #[link_name = "igGetWindowViewport"]
    fn c_igGetWindowViewport() -> *mut c_void;
    #[link_name = "igGetWindowWidth"]
    fn c_igGetWindowWidth() -> f32;
    #[link_name = "igIndent"]
    fn c_igIndent(arg0: f32) -> ();
    #[link_name = "igInputDouble"]
    fn c_igInputDouble(arg0: *const c_char, arg1: *mut c_double, arg2: c_double, arg3: c_double, arg4: *const c_char, arg5: c_int) -> bool;
    #[link_name = "igInputFloat"]
    fn c_igInputFloat(arg0: *const c_char, arg1: *mut f32, arg2: f32, arg3: f32, arg4: *const c_char, arg5: c_int) -> bool;
    #[link_name = "igInputFloat3"]
    fn c_igInputFloat3(arg0: *const c_char, arg1: *mut f32, arg2: *const c_char, arg3: c_int) -> bool;
    #[link_name = "igInputFloat4"]
    fn c_igInputFloat4(arg0: *const c_char, arg1: *mut f32, arg2: *const c_char, arg3: c_int) -> bool;
    #[link_name = "igInputInt"]
    fn c_igInputInt(arg0: *const c_char, arg1: *mut c_int, arg2: c_int, arg3: c_int, arg4: c_int) -> bool;
    #[link_name = "igInputText"]
    fn c_igInputText(arg0: *const c_char, arg1: *mut c_char, arg2: usize, arg3: c_int, arg4: *mut c_void, arg5: *mut c_void) -> bool;
    #[link_name = "igInputTextMultiline"]
    fn c_igInputTextMultiline(arg0: *const c_char, arg1: *mut c_char, arg2: usize, arg3: ImVec2, arg4: c_int, arg5: *mut c_void, arg6: *mut c_void) -> bool;
    #[link_name = "igInputTextWithHint"]
    fn c_igInputTextWithHint(arg0: *const c_char, arg1: *const c_char, arg2: *mut c_char, arg3: usize, arg4: c_int, arg5: *mut c_void, arg6: *mut c_void) -> bool;
    #[link_name = "igInvisibleButton"]
    fn c_igInvisibleButton(arg0: *const c_char, arg1: ImVec2, arg2: c_int) -> bool;
    #[link_name = "igIsAnyItemActive"]
    fn c_igIsAnyItemActive() -> bool;
    #[link_name = "igIsAnyItemFocused"]
    fn c_igIsAnyItemFocused() -> bool;
    #[link_name = "igIsAnyItemHovered"]
    fn c_igIsAnyItemHovered() -> bool;
    #[link_name = "igIsAnyMouseDown"]
    fn c_igIsAnyMouseDown() -> bool;
    #[link_name = "igIsItemActivated"]
    fn c_igIsItemActivated() -> bool;
    #[link_name = "igIsItemActive"]
    fn c_igIsItemActive() -> bool;
    #[link_name = "igIsItemClicked"]
    fn c_igIsItemClicked(arg0: c_int) -> bool;
    #[link_name = "igIsItemDeactivated"]
    fn c_igIsItemDeactivated() -> bool;
    #[link_name = "igIsItemDeactivatedAfterEdit"]
    fn c_igIsItemDeactivatedAfterEdit() -> bool;
    #[link_name = "igIsItemEdited"]
    fn c_igIsItemEdited() -> bool;
    #[link_name = "igIsItemFocused"]
    fn c_igIsItemFocused() -> bool;
    #[link_name = "igIsItemHovered"]
    fn c_igIsItemHovered(arg0: c_int) -> bool;
    #[link_name = "igIsItemToggledOpen"]
    fn c_igIsItemToggledOpen() -> bool;
    #[link_name = "igIsItemToggledSelection"]
    fn c_igIsItemToggledSelection() -> bool;
    #[link_name = "igIsItemVisible"]
    fn c_igIsItemVisible() -> bool;
    #[link_name = "igIsKeyDown"]
    fn c_igIsKeyDown(arg0: c_int) -> bool;
    #[link_name = "igIsKeyPressed"]
    fn c_igIsKeyPressed(arg0: c_int, arg1: bool) -> bool;
    #[link_name = "igIsKeyReleased"]
    fn c_igIsKeyReleased(arg0: c_int) -> bool;
    #[link_name = "igIsMouseClicked"]
    fn c_igIsMouseClicked(arg0: c_int, arg1: bool) -> bool;
    #[link_name = "igIsMouseDoubleClicked"]
    fn c_igIsMouseDoubleClicked(arg0: c_int) -> bool;
    #[link_name = "igIsMouseDown"]
    fn c_igIsMouseDown(arg0: c_int) -> bool;
    #[link_name = "igIsMouseDragging"]
    fn c_igIsMouseDragging(arg0: c_int, arg1: f32) -> bool;
    #[link_name = "igIsMouseHoveringRect"]
    fn c_igIsMouseHoveringRect(arg0: ImVec2, arg1: ImVec2, arg2: bool) -> bool;
    #[link_name = "igIsMousePosValid"]
    fn c_igIsMousePosValid(arg0: *const c_void) -> bool;
    #[link_name = "igIsMouseReleased"]
    fn c_igIsMouseReleased(arg0: c_int) -> bool;
    #[link_name = "igIsMouseReleasedWithDelay"]
    fn c_igIsMouseReleasedWithDelay(arg0: c_int, arg1: f32) -> bool;
    #[link_name = "igIsPopupOpen"]
    fn c_igIsPopupOpen(arg0: *const c_char, arg1: c_int) -> bool;
    #[link_name = "igIsRectVisible"]
    fn c_igIsRectVisible(arg0: ImVec2, arg1: ImVec2) -> bool;
    #[link_name = "igIsRectVisibleBySize"]
    fn c_igIsRectVisibleBySize(arg0: ImVec2) -> bool;
    #[link_name = "igIsWindowAppearing"]
    fn c_igIsWindowAppearing() -> bool;
    #[link_name = "igIsWindowCollapsed"]
    fn c_igIsWindowCollapsed() -> bool;
    #[link_name = "igIsWindowDocked"]
    fn c_igIsWindowDocked() -> bool;
    #[link_name = "igIsWindowFocused"]
    fn c_igIsWindowFocused(arg0: c_int) -> bool;
    #[link_name = "igIsWindowHovered"]
    fn c_igIsWindowHovered(arg0: c_int) -> bool;
    #[link_name = "igListBox"]
    fn c_igListBox(arg0: *const c_char, arg1: *mut c_int, arg2: *const *const c_char, arg3: c_int, arg4: c_int) -> bool;
    #[link_name = "igLoadIniSettingsFromDisk"]
    fn c_igLoadIniSettingsFromDisk(arg0: *const c_char) -> ();
    #[link_name = "igLoadIniSettingsFromMemory"]
    fn c_igLoadIniSettingsFromMemory(arg0: *const c_char, arg1: usize) -> ();
    #[link_name = "igLogButtons"]
    fn c_igLogButtons() -> ();
    #[link_name = "igLogFinish"]
    fn c_igLogFinish() -> ();
    #[link_name = "igLogToClipboard"]
    fn c_igLogToClipboard(arg0: c_int) -> ();
    #[link_name = "igLogToFile"]
    fn c_igLogToFile(arg0: c_int, arg1: *const c_char) -> ();
    #[link_name = "igLogToTTY"]
    fn c_igLogToTTY(arg0: c_int) -> ();
    #[link_name = "igMemAlloc"]
    fn c_igMemAlloc(arg0: usize) -> *mut c_void;
    #[link_name = "igMemFree"]
    fn c_igMemFree(arg0: *mut c_void) -> ();
    #[link_name = "igMenuItem"]
    fn c_igMenuItem(arg0: *const c_char, arg1: *const c_char, arg2: bool, arg3: bool) -> bool;
    #[link_name = "igMenuItemBoolPtr"]
    fn c_igMenuItemBoolPtr(arg0: *const c_char, arg1: *const c_char, arg2: *mut bool, arg3: bool) -> bool;
    #[link_name = "igNewFrame"]
    fn c_igNewFrame() -> ();
    #[link_name = "igNewLine"]
    fn c_igNewLine() -> ();
    #[link_name = "igNextColumn"]
    fn c_igNextColumn() -> ();
    #[link_name = "igOpenPopup"]
    fn c_igOpenPopup(arg0: *const c_char, arg1: c_int) -> ();
    #[link_name = "igOpenPopupID"]
    fn c_igOpenPopupID(arg0: c_uint, arg1: c_int) -> ();
    #[link_name = "igOpenPopupOnItemClick"]
    fn c_igOpenPopupOnItemClick(arg0: *const c_char, arg1: c_int) -> ();
    #[link_name = "igPlotHistogram"]
    fn c_igPlotHistogram(arg0: *const c_char, arg1: *const f32, arg2: c_int, arg3: c_int, arg4: *const c_char, arg5: f32, arg6: f32, arg7: ImVec2, arg8: c_int) -> ();
    #[link_name = "igPlotLines"]
    fn c_igPlotLines(arg0: *const c_char, arg1: *const f32, arg2: c_int, arg3: c_int, arg4: *const c_char, arg5: f32, arg6: f32, arg7: ImVec2, arg8: c_int) -> ();
    #[link_name = "igPopButtonRepeat"]
    fn c_igPopButtonRepeat() -> ();
    #[link_name = "igPopClipRect"]
    fn c_igPopClipRect() -> ();
    #[link_name = "igPopFont"]
    fn c_igPopFont() -> ();
    #[link_name = "igPopID"]
    fn c_igPopID() -> ();
    #[link_name = "igPopItemFlag"]
    fn c_igPopItemFlag() -> ();
    #[link_name = "igPopItemWidth"]
    fn c_igPopItemWidth() -> ();
    #[link_name = "igPopStyleColor"]
    fn c_igPopStyleColor(arg0: c_int) -> ();
    #[link_name = "igPopStyleVar"]
    fn c_igPopStyleVar(arg0: c_int) -> ();
    #[link_name = "igPopTabStop"]
    fn c_igPopTabStop() -> ();
    #[link_name = "igPopTextWrapPos"]
    fn c_igPopTextWrapPos() -> ();
    #[link_name = "igProgressBar"]
    fn c_igProgressBar(arg0: f32, arg1: ImVec2, arg2: *const c_char) -> ();
    #[link_name = "igPushButtonRepeat"]
    fn c_igPushButtonRepeat(arg0: bool) -> ();
    #[link_name = "igPushClipRect"]
    fn c_igPushClipRect(arg0: ImVec2, arg1: ImVec2, arg2: bool) -> ();
    #[link_name = "igPushFont"]
    fn c_igPushFont(arg0: *mut c_void) -> ();
    #[link_name = "igPushFontFloat"]
    fn c_igPushFontFloat(arg0: *mut c_void, arg1: f32) -> ();
    #[link_name = "igPushID"]
    fn c_igPushID(arg0: *const c_char) -> ();
    #[link_name = "igPushIDInt"]
    fn c_igPushIDInt(arg0: c_int) -> ();
    #[link_name = "igPushIDPtr"]
    fn c_igPushIDPtr(arg0: *const c_void) -> ();
    #[link_name = "igPushIDStr"]
    fn c_igPushIDStr(arg0: *const c_char, arg1: *const c_char) -> ();
    #[link_name = "igPushItemFlag"]
    fn c_igPushItemFlag(arg0: c_int, arg1: bool) -> ();
    #[link_name = "igPushItemWidth"]
    fn c_igPushItemWidth(arg0: f32) -> ();
    #[link_name = "igPushTabStop"]
    fn c_igPushTabStop(arg0: bool) -> ();
    #[link_name = "igPushTextWrapPos"]
    fn c_igPushTextWrapPos(arg0: f32) -> ();
    #[link_name = "igRadioButton"]
    fn c_igRadioButton(arg0: *const c_char, arg1: bool) -> bool;
    #[link_name = "igRadioButtonIntPtr"]
    fn c_igRadioButtonIntPtr(arg0: *const c_char, arg1: *mut c_int, arg2: c_int) -> bool;
    #[link_name = "igRender"]
    fn c_igRender() -> ();
    #[link_name = "igRenderPlatformWindowsDefault"]
    fn c_igRenderPlatformWindowsDefault(arg0: *mut c_void, arg1: *mut c_void) -> ();
    #[link_name = "igResetMouseDragDelta"]
    fn c_igResetMouseDragDelta(arg0: c_int) -> ();
    #[link_name = "igSameLine"]
    fn c_igSameLine(arg0: f32, arg1: f32) -> ();
    #[link_name = "igSaveIniSettingsToDisk"]
    fn c_igSaveIniSettingsToDisk(arg0: *const c_char) -> ();
    #[link_name = "igSaveIniSettingsToMemory"]
    fn c_igSaveIniSettingsToMemory(arg0: *mut usize) -> *const c_char;
    #[link_name = "igSelectable"]
    fn c_igSelectable(arg0: *const c_char, arg1: bool, arg2: c_int, arg3: ImVec2) -> bool;
    #[link_name = "igSelectableBoolPtr"]
    fn c_igSelectableBoolPtr(arg0: *const c_char, arg1: *mut bool, arg2: c_int, arg3: ImVec2) -> bool;
    #[link_name = "igSeparator"]
    fn c_igSeparator() -> ();
    #[link_name = "igSeparatorText"]
    fn c_igSeparatorText(arg0: *const c_char) -> ();
    #[link_name = "igSetClipboardText"]
    fn c_igSetClipboardText(arg0: *const c_char) -> ();
    #[link_name = "igSetColorEditOptions"]
    fn c_igSetColorEditOptions(arg0: c_int) -> ();
    #[link_name = "igSetColumnOffset"]
    fn c_igSetColumnOffset(arg0: c_int, arg1: f32) -> ();
    #[link_name = "igSetColumnWidth"]
    fn c_igSetColumnWidth(arg0: c_int, arg1: f32) -> ();
    #[link_name = "igSetCurrentContext"]
    fn c_igSetCurrentContext(arg0: *mut c_void) -> ();
    #[link_name = "igSetCursorPos"]
    fn c_igSetCursorPos(arg0: ImVec2) -> ();
    #[link_name = "igSetCursorPosX"]
    fn c_igSetCursorPosX(arg0: f32) -> ();
    #[link_name = "igSetCursorPosY"]
    fn c_igSetCursorPosY(arg0: f32) -> ();
    #[link_name = "igSetCursorScreenPos"]
    fn c_igSetCursorScreenPos(arg0: ImVec2) -> ();
    #[link_name = "igSetItemDefaultFocus"]
    fn c_igSetItemDefaultFocus() -> ();
    #[link_name = "igSetItemKeyOwner"]
    fn c_igSetItemKeyOwner(arg0: c_int) -> bool;
    #[link_name = "igSetKeyboardFocusHere"]
    fn c_igSetKeyboardFocusHere(arg0: c_int) -> ();
    #[link_name = "igSetMouseCursor"]
    fn c_igSetMouseCursor(arg0: c_int) -> ();
    #[link_name = "igSetNavCursorVisible"]
    fn c_igSetNavCursorVisible(arg0: bool) -> ();
    #[link_name = "igSetNextFrameWantCaptureKeyboard"]
    fn c_igSetNextFrameWantCaptureKeyboard(arg0: bool) -> ();
    #[link_name = "igSetNextFrameWantCaptureMouse"]
    fn c_igSetNextFrameWantCaptureMouse(arg0: bool) -> ();
    #[link_name = "igSetNextItemAllowOverlap"]
    fn c_igSetNextItemAllowOverlap() -> ();
    #[link_name = "igSetNextItemStorageID"]
    fn c_igSetNextItemStorageID(arg0: c_uint) -> ();
    #[link_name = "igSetNextItemWidth"]
    fn c_igSetNextItemWidth(arg0: f32) -> ();
    #[link_name = "igSetNextWindowBgAlpha"]
    fn c_igSetNextWindowBgAlpha(arg0: f32) -> ();
    #[link_name = "igSetNextWindowClass"]
    fn c_igSetNextWindowClass(arg0: *const c_void) -> ();
    #[link_name = "igSetNextWindowContentSize"]
    fn c_igSetNextWindowContentSize(arg0: ImVec2) -> ();
    #[link_name = "igSetNextWindowFocus"]
    fn c_igSetNextWindowFocus() -> ();
    #[link_name = "igSetNextWindowScroll"]
    fn c_igSetNextWindowScroll(arg0: ImVec2) -> ();
    #[link_name = "igSetNextWindowSizeConstraints"]
    fn c_igSetNextWindowSizeConstraints(arg0: ImVec2, arg1: ImVec2, arg2: *mut c_void, arg3: *mut c_void) -> ();
    #[link_name = "igSetNextWindowViewport"]
    fn c_igSetNextWindowViewport(arg0: c_uint) -> ();
    #[link_name = "igSetScrollFromPosX"]
    fn c_igSetScrollFromPosX(arg0: f32, arg1: f32) -> ();
    #[link_name = "igSetScrollFromPosY"]
    fn c_igSetScrollFromPosY(arg0: f32, arg1: f32) -> ();
    #[link_name = "igSetScrollHereX"]
    fn c_igSetScrollHereX(arg0: f32) -> ();
    #[link_name = "igSetScrollHereY"]
    fn c_igSetScrollHereY(arg0: f32) -> ();
    #[link_name = "igSetScrollX"]
    fn c_igSetScrollX(arg0: f32) -> ();
    #[link_name = "igSetScrollY"]
    fn c_igSetScrollY(arg0: f32) -> ();
    #[link_name = "igSetStateStorage"]
    fn c_igSetStateStorage(arg0: *mut c_void) -> ();
    #[link_name = "igSetTabItemClosed"]
    fn c_igSetTabItemClosed(arg0: *const c_char) -> ();
    #[link_name = "igSetWindowFocus"]
    fn c_igSetWindowFocus() -> ();
    #[link_name = "igSetWindowFocusStr"]
    fn c_igSetWindowFocusStr(arg0: *const c_char) -> ();
    #[link_name = "igSetWindowFontScale"]
    fn c_igSetWindowFontScale(arg0: f32) -> ();
    #[link_name = "igShowAboutWindow"]
    fn c_igShowAboutWindow(arg0: *mut bool) -> ();
    #[link_name = "igShowDebugLogWindow"]
    fn c_igShowDebugLogWindow(arg0: *mut bool) -> ();
    #[link_name = "igShowDemoWindow"]
    fn c_igShowDemoWindow(arg0: *mut bool) -> ();
    #[link_name = "igShowFontSelector"]
    fn c_igShowFontSelector(arg0: *const c_char) -> ();
    #[link_name = "igShowIDStackToolWindow"]
    fn c_igShowIDStackToolWindow(arg0: *mut bool) -> ();
    #[link_name = "igShowMetricsWindow"]
    fn c_igShowMetricsWindow(arg0: *mut bool) -> ();
    #[link_name = "igShowStyleEditor"]
    fn c_igShowStyleEditor(arg0: *mut c_void) -> ();
    #[link_name = "igShowStyleSelector"]
    fn c_igShowStyleSelector(arg0: *const c_char) -> bool;
    #[link_name = "igShowUserGuide"]
    fn c_igShowUserGuide() -> ();
    #[link_name = "igSliderAngle"]
    fn c_igSliderAngle(arg0: *const c_char, arg1: *mut f32, arg2: f32, arg3: f32, arg4: *const c_char, arg5: c_int) -> bool;
    #[link_name = "igSliderFloat"]
    fn c_igSliderFloat(arg0: *const c_char, arg1: *mut f32, arg2: f32, arg3: f32, arg4: *const c_char, arg5: c_int) -> bool;
    #[link_name = "igSliderFloat3"]
    fn c_igSliderFloat3(arg0: *const c_char, arg1: *mut f32, arg2: f32, arg3: f32, arg4: *const c_char, arg5: c_int) -> bool;
    #[link_name = "igSliderFloat4"]
    fn c_igSliderFloat4(arg0: *const c_char, arg1: *mut f32, arg2: f32, arg3: f32, arg4: *const c_char, arg5: c_int) -> bool;
    #[link_name = "igSliderInt"]
    fn c_igSliderInt(arg0: *const c_char, arg1: *mut c_int, arg2: c_int, arg3: c_int, arg4: *const c_char, arg5: c_int) -> bool;
    #[link_name = "igSmallButton"]
    fn c_igSmallButton(arg0: *const c_char) -> bool;
    #[link_name = "igSpacing"]
    fn c_igSpacing() -> ();
    #[link_name = "igStyleColorsClassic"]
    fn c_igStyleColorsClassic(arg0: *mut c_void) -> ();
    #[link_name = "igStyleColorsDark"]
    fn c_igStyleColorsDark(arg0: *mut c_void) -> ();
    #[link_name = "igStyleColorsLight"]
    fn c_igStyleColorsLight(arg0: *mut c_void) -> ();
    #[link_name = "igTabItemButton"]
    fn c_igTabItemButton(arg0: *const c_char, arg1: c_int) -> bool;
    #[link_name = "igTableAngledHeadersRow"]
    fn c_igTableAngledHeadersRow() -> ();
    #[link_name = "igTableGetColumnCount"]
    fn c_igTableGetColumnCount() -> c_int;
    #[link_name = "igTableGetColumnFlags"]
    fn c_igTableGetColumnFlags(arg0: c_int) -> c_int;
    #[link_name = "igTableGetColumnIndex"]
    fn c_igTableGetColumnIndex() -> c_int;
    #[link_name = "igTableGetColumnName"]
    fn c_igTableGetColumnName(arg0: c_int) -> *const c_char;
    #[link_name = "igTableGetHoveredColumn"]
    fn c_igTableGetHoveredColumn() -> c_int;
    #[link_name = "igTableGetRowIndex"]
    fn c_igTableGetRowIndex() -> c_int;
    #[link_name = "igTableGetSortSpecs"]
    fn c_igTableGetSortSpecs() -> *mut c_void;
    #[link_name = "igTableHeader"]
    fn c_igTableHeader(arg0: *const c_char) -> ();
    #[link_name = "igTableHeadersRow"]
    fn c_igTableHeadersRow() -> ();
    #[link_name = "igTableNextColumn"]
    fn c_igTableNextColumn() -> bool;
    #[link_name = "igTableNextRow"]
    fn c_igTableNextRow(arg0: c_int, arg1: f32) -> ();
    #[link_name = "igTableSetColumnEnabled"]
    fn c_igTableSetColumnEnabled(arg0: c_int, arg1: bool) -> ();
    #[link_name = "igTableSetColumnIndex"]
    fn c_igTableSetColumnIndex(arg0: c_int) -> bool;
    #[link_name = "igTableSetupColumn"]
    fn c_igTableSetupColumn(arg0: *const c_char, arg1: c_int, arg2: f32, arg3: c_uint) -> ();
    #[link_name = "igTableSetupScrollFreeze"]
    fn c_igTableSetupScrollFreeze(arg0: c_int, arg1: c_int) -> ();
    #[link_name = "igTextLink"]
    fn c_igTextLink(arg0: *const c_char) -> bool;
    #[link_name = "igTextLinkOpenURL"]
    fn c_igTextLinkOpenURL(arg0: *const c_char, arg1: *const c_char) -> bool;
    #[link_name = "igTextUnformatted"]
    fn c_igTextUnformatted(arg0: *const c_char, arg1: *const c_char) -> ();
    #[link_name = "igTreeNode"]
    fn c_igTreeNode(arg0: *const c_char) -> bool;
    #[link_name = "igTreeNodeEx"]
    fn c_igTreeNodeEx(arg0: *const c_char, arg1: c_int) -> bool;
    #[link_name = "igTreeNodeGetOpen"]
    fn c_igTreeNodeGetOpen(arg0: c_uint) -> bool;
    #[link_name = "igTreePop"]
    fn c_igTreePop() -> ();
    #[link_name = "igTreePush"]
    fn c_igTreePush(arg0: *const c_char) -> ();
    #[link_name = "igTreePushPtr"]
    fn c_igTreePushPtr(arg0: *const c_void) -> ();
    #[link_name = "igUnindent"]
    fn c_igUnindent(arg0: f32) -> ();
    #[link_name = "igUpdatePlatformWindows"]
    fn c_igUpdatePlatformWindows() -> ();
    #[link_name = "igVSliderFloat"]
    fn c_igVSliderFloat(arg0: *const c_char, arg1: ImVec2, arg2: *mut f32, arg3: f32, arg4: f32, arg5: *const c_char, arg6: c_int) -> bool;
    #[link_name = "igVSliderInt"]
    fn c_igVSliderInt(arg0: *const c_char, arg1: ImVec2, arg2: *mut c_int, arg3: c_int, arg4: c_int, arg5: *const c_char, arg6: c_int) -> bool;
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igAcceptDragDropPayload(arg0: *const c_char, arg1: c_int) -> *const c_void {
    c_igAcceptDragDropPayload(arg0, arg1)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igAlignTextToFramePadding() -> () {
    c_igAlignTextToFramePadding();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igArrowButton(arg0: *const c_char, arg1: c_int) -> bool {
    c_igArrowButton(arg0, arg1)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igBegin(arg0: *const c_char, arg1: *mut bool, arg2: c_int) -> bool {
    c_igBegin(arg0, arg1, arg2)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igBeginChild(arg0: *const c_char, arg1: ImVec2, arg2: c_int, arg3: c_int) -> bool {
    c_igBeginChild(arg0, arg1, arg2, arg3)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igBeginChildID(arg0: c_uint, arg1: ImVec2, arg2: c_int, arg3: c_int) -> bool {
    c_igBeginChildID(arg0, arg1, arg2, arg3)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igBeginCombo(arg0: *const c_char, arg1: *const c_char, arg2: c_int) -> bool {
    c_igBeginCombo(arg0, arg1, arg2)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igBeginDisabled(arg0: bool) -> () {
    c_igBeginDisabled(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igBeginDragDropSource(arg0: c_int) -> bool {
    c_igBeginDragDropSource(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igBeginDragDropTarget() -> bool {
    c_igBeginDragDropTarget()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igBeginGroup() -> () {
    c_igBeginGroup();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igBeginItemTooltip() -> bool {
    c_igBeginItemTooltip()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igBeginListBox(arg0: *const c_char, arg1: ImVec2) -> bool {
    c_igBeginListBox(arg0, arg1)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igBeginMainMenuBar() -> bool {
    c_igBeginMainMenuBar()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igBeginMenu(arg0: *const c_char, arg1: bool) -> bool {
    c_igBeginMenu(arg0, arg1)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igBeginMenuBar() -> bool {
    c_igBeginMenuBar()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igBeginMultiSelect(arg0: c_int, arg1: c_int, arg2: c_int) -> *mut c_void {
    c_igBeginMultiSelect(arg0, arg1, arg2)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igBeginPopup(arg0: *const c_char, arg1: c_int) -> bool {
    c_igBeginPopup(arg0, arg1)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igBeginPopupContextItem(arg0: *const c_char, arg1: c_int) -> bool {
    c_igBeginPopupContextItem(arg0, arg1)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igBeginPopupContextVoid(arg0: *const c_char, arg1: c_int) -> bool {
    c_igBeginPopupContextVoid(arg0, arg1)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igBeginPopupContextWindow(arg0: *const c_char, arg1: c_int) -> bool {
    c_igBeginPopupContextWindow(arg0, arg1)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igBeginPopupModal(arg0: *const c_char, arg1: *mut bool, arg2: c_int) -> bool {
    c_igBeginPopupModal(arg0, arg1, arg2)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igBeginTabBar(arg0: *const c_char, arg1: c_int) -> bool {
    c_igBeginTabBar(arg0, arg1)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igBeginTabItem(arg0: *const c_char, arg1: *mut bool, arg2: c_int) -> bool {
    c_igBeginTabItem(arg0, arg1, arg2)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igBeginTable(arg0: *const c_char, arg1: c_int, arg2: c_int, arg3: ImVec2, arg4: f32) -> bool {
    c_igBeginTable(arg0, arg1, arg2, arg3, arg4)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igBeginTooltip() -> bool {
    c_igBeginTooltip()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igBullet() -> () {
    c_igBullet();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igButton(arg0: *const c_char, arg1: ImVec2) -> bool {
    c_igButton(arg0, arg1)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igCalcItemWidth() -> f32 {
    c_igCalcItemWidth()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igCalcTextSize(arg0: *const c_char, arg1: *const c_char, arg2: bool, arg3: f32) -> ImVec2 {
    c_igCalcTextSize(arg0, arg1, arg2, arg3)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igCheckbox(arg0: *const c_char, arg1: *mut bool) -> bool {
    c_igCheckbox(arg0, arg1)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igCheckboxFlagsIntPtr(arg0: *const c_char, arg1: *mut c_int, arg2: c_int) -> bool {
    c_igCheckboxFlagsIntPtr(arg0, arg1, arg2)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igCheckboxFlagsUintPtr(arg0: *const c_char, arg1: *mut c_uint, arg2: c_uint) -> bool {
    c_igCheckboxFlagsUintPtr(arg0, arg1, arg2)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igCloseCurrentPopup() -> () {
    c_igCloseCurrentPopup();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igCollapsingHeader(arg0: *const c_char, arg1: c_int) -> bool {
    c_igCollapsingHeader(arg0, arg1)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igCollapsingHeaderBoolPtr(arg0: *const c_char, arg1: *mut bool, arg2: c_int) -> bool {
    c_igCollapsingHeaderBoolPtr(arg0, arg1, arg2)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igColorButton(arg0: *const c_char, arg1: ImVec4, arg2: c_int, arg3: ImVec2) -> bool {
    c_igColorButton(arg0, arg1, arg2, arg3)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igColorConvertFloat4ToU32(arg0: ImVec4) -> u32 {
    c_igColorConvertFloat4ToU32(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igColorConvertHSVtoRGB(arg0: f32, arg1: f32, arg2: f32, arg3: *mut f32, arg4: *mut f32, arg5: *mut f32) -> () {
    c_igColorConvertHSVtoRGB(arg0, arg1, arg2, arg3, arg4, arg5);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igColorConvertRGBtoHSV(arg0: f32, arg1: f32, arg2: f32, arg3: *mut f32, arg4: *mut f32, arg5: *mut f32) -> () {
    c_igColorConvertRGBtoHSV(arg0, arg1, arg2, arg3, arg4, arg5);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igColorConvertU32ToFloat4(arg0: u32) -> ImVec4 {
    c_igColorConvertU32ToFloat4(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igColorEdit3(arg0: *const c_char, arg1: *mut f32, arg2: c_int) -> bool {
    c_igColorEdit3(arg0, arg1, arg2)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igColorEdit4(arg0: *const c_char, arg1: *mut f32, arg2: c_int) -> bool {
    c_igColorEdit4(arg0, arg1, arg2)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igColorPicker3(arg0: *const c_char, arg1: *mut f32, arg2: c_int) -> bool {
    c_igColorPicker3(arg0, arg1, arg2)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igColorPicker4(arg0: *const c_char, arg1: *mut f32, arg2: c_int, arg3: *const f32) -> bool {
    c_igColorPicker4(arg0, arg1, arg2, arg3)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igColumns(arg0: c_int, arg1: *const c_char, arg2: bool) -> () {
    c_igColumns(arg0, arg1, arg2);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igCombo(arg0: *const c_char, arg1: *mut c_int, arg2: *const c_char, arg3: c_int) -> bool {
    c_igCombo(arg0, arg1, arg2, arg3)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igComboChar(arg0: *const c_char, arg1: *mut c_int, arg2: *const *const c_char, arg3: c_int, arg4: c_int) -> bool {
    c_igComboChar(arg0, arg1, arg2, arg3, arg4)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igCreateContext(arg0: *mut c_void) -> *mut c_void {
    c_igCreateContext(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igDebugCheckVersionAndDataLayout(arg0: *const c_char, arg1: usize, arg2: usize, arg3: usize, arg4: usize, arg5: usize, arg6: usize) -> bool {
    c_igDebugCheckVersionAndDataLayout(arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igDebugStartItemPicker() -> () {
    c_igDebugStartItemPicker();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igDebugTextEncoding(arg0: *const c_char) -> () {
    c_igDebugTextEncoding(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igDestroyContext(arg0: *mut c_void) -> () {
    c_igDestroyContext(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igDestroyPlatformWindows() -> () {
    c_igDestroyPlatformWindows();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igDockSpace(arg0: c_uint, arg1: ImVec2, arg2: c_int, arg3: *const c_void) -> c_uint {
    c_igDockSpace(arg0, arg1, arg2, arg3)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igDockSpaceOverViewport(arg0: c_uint, arg1: *const c_void, arg2: c_int, arg3: *const c_void) -> c_uint {
    c_igDockSpaceOverViewport(arg0, arg1, arg2, arg3)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igDragFloat(arg0: *const c_char, arg1: *mut f32, arg2: f32, arg3: f32, arg4: f32, arg5: *const c_char, arg6: c_int) -> bool {
    c_igDragFloat(arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igDragFloat3(arg0: *const c_char, arg1: *mut f32, arg2: f32, arg3: f32, arg4: f32, arg5: *const c_char, arg6: c_int) -> bool {
    c_igDragFloat3(arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igDragFloat4(arg0: *const c_char, arg1: *mut f32, arg2: f32, arg3: f32, arg4: f32, arg5: *const c_char, arg6: c_int) -> bool {
    c_igDragFloat4(arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igDragFloatRange2(arg0: *const c_char, arg1: *mut f32, arg2: *mut f32, arg3: f32, arg4: f32, arg5: f32, arg6: *const c_char, arg7: *const c_char, arg8: c_int) -> bool {
    c_igDragFloatRange2(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igDragInt(arg0: *const c_char, arg1: *mut c_int, arg2: f32, arg3: c_int, arg4: c_int, arg5: *const c_char, arg6: c_int) -> bool {
    c_igDragInt(arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igDragIntRange2(arg0: *const c_char, arg1: *mut c_int, arg2: *mut c_int, arg3: f32, arg4: c_int, arg5: c_int, arg6: *const c_char, arg7: *const c_char, arg8: c_int) -> bool {
    c_igDragIntRange2(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igDummy(arg0: ImVec2) -> () {
    c_igDummy(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igEnd() -> () {
    c_igEnd();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igEndChild() -> () {
    c_igEndChild();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igEndCombo() -> () {
    c_igEndCombo();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igEndDisabled() -> () {
    c_igEndDisabled();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igEndDragDropSource() -> () {
    c_igEndDragDropSource();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igEndDragDropTarget() -> () {
    c_igEndDragDropTarget();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igEndFrame() -> () {
    c_igEndFrame();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igEndGroup() -> () {
    c_igEndGroup();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igEndListBox() -> () {
    c_igEndListBox();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igEndMainMenuBar() -> () {
    c_igEndMainMenuBar();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igEndMenu() -> () {
    c_igEndMenu();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igEndMenuBar() -> () {
    c_igEndMenuBar();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igEndMultiSelect() -> *mut c_void {
    c_igEndMultiSelect()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igEndPopup() -> () {
    c_igEndPopup();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igEndTabBar() -> () {
    c_igEndTabBar();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igEndTabItem() -> () {
    c_igEndTabItem();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igEndTable() -> () {
    c_igEndTable();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igEndTooltip() -> () {
    c_igEndTooltip();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igFindViewportByID(arg0: c_uint) -> *mut c_void {
    c_igFindViewportByID(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igFindViewportByPlatformHandle(arg0: *mut c_void) -> *mut c_void {
    c_igFindViewportByPlatformHandle(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetAllocatorFunctions(arg0: *mut c_void, arg1: *mut c_void, arg2: *mut *mut c_void) -> () {
    c_igGetAllocatorFunctions(arg0, arg1, arg2);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetBackgroundDrawList(arg0: *mut c_void) -> *mut c_void {
    c_igGetBackgroundDrawList(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetClipboardText() -> *const c_char {
    c_igGetClipboardText()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetColorU32ImU32(arg0: u32, arg1: f32) -> u32 {
    c_igGetColorU32ImU32(arg0, arg1)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetColorU32ImVec4(arg0: ImVec4) -> u32 {
    c_igGetColorU32ImVec4(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetColumnIndex() -> c_int {
    c_igGetColumnIndex()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetColumnOffset(arg0: c_int) -> f32 {
    c_igGetColumnOffset(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetColumnWidth(arg0: c_int) -> f32 {
    c_igGetColumnWidth(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetColumnsCount() -> c_int {
    c_igGetColumnsCount()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetContentRegionAvail() -> ImVec2 {
    c_igGetContentRegionAvail()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetContentRegionMax() -> ImVec2 {
    c_igGetContentRegionMax()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetCurrentContext() -> *mut c_void {
    c_igGetCurrentContext()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetCursorPos() -> ImVec2 {
    c_igGetCursorPos()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetCursorPosX() -> f32 {
    c_igGetCursorPosX()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetCursorPosY() -> f32 {
    c_igGetCursorPosY()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetCursorScreenPos() -> ImVec2 {
    c_igGetCursorScreenPos()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetCursorStartPos() -> ImVec2 {
    c_igGetCursorStartPos()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetDragDropPayload() -> *const c_void {
    c_igGetDragDropPayload()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetDrawData() -> *mut c_void {
    c_igGetDrawData()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetDrawListSharedData() -> *mut c_void {
    c_igGetDrawListSharedData()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetFont() -> *mut c_void {
    c_igGetFont()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetFontBaked() -> *mut c_void {
    c_igGetFontBaked()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetFontSize() -> f32 {
    c_igGetFontSize()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetFontTexUvWhitePixel() -> ImVec2 {
    c_igGetFontTexUvWhitePixel()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetForegroundDrawList(arg0: *mut c_void) -> *mut c_void {
    c_igGetForegroundDrawList(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetFrameCount() -> c_int {
    c_igGetFrameCount()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetFrameHeight() -> f32 {
    c_igGetFrameHeight()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetFrameHeightWithSpacing() -> f32 {
    c_igGetFrameHeightWithSpacing()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetID(arg0: *const c_char) -> c_uint {
    c_igGetID(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetIDInt(arg0: c_int) -> c_uint {
    c_igGetIDInt(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetIDPtr(arg0: *const c_void) -> c_uint {
    c_igGetIDPtr(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetIDStr(arg0: *const c_char, arg1: *const c_char) -> c_uint {
    c_igGetIDStr(arg0, arg1)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetIO() -> *mut c_void {
    c_igGetIO()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetItemFlags() -> c_int {
    c_igGetItemFlags()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetItemID() -> c_uint {
    c_igGetItemID()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetItemRectMax() -> ImVec2 {
    c_igGetItemRectMax()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetItemRectMin() -> ImVec2 {
    c_igGetItemRectMin()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetItemRectSize() -> ImVec2 {
    c_igGetItemRectSize()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetKeyName(arg0: c_int) -> *const c_char {
    c_igGetKeyName(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetKeyPressedAmount(arg0: c_int, arg1: f32, arg2: f32) -> c_int {
    c_igGetKeyPressedAmount(arg0, arg1, arg2)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetMainViewport() -> *mut c_void {
    c_igGetMainViewport()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetMouseClickedCount(arg0: c_int) -> c_int {
    c_igGetMouseClickedCount(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetMouseCursor() -> c_int {
    c_igGetMouseCursor()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetMouseDragDelta(arg0: c_int, arg1: f32) -> ImVec2 {
    c_igGetMouseDragDelta(arg0, arg1)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetMousePos() -> ImVec2 {
    c_igGetMousePos()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetMousePosOnOpeningCurrentPopup() -> ImVec2 {
    c_igGetMousePosOnOpeningCurrentPopup()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetPlatformIO() -> *mut c_void {
    c_igGetPlatformIO()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetScrollMaxX() -> f32 {
    c_igGetScrollMaxX()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetScrollMaxY() -> f32 {
    c_igGetScrollMaxY()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetScrollX() -> f32 {
    c_igGetScrollX()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetScrollY() -> f32 {
    c_igGetScrollY()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetStateStorage() -> *mut c_void {
    c_igGetStateStorage()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetStyle() -> *mut c_void {
    c_igGetStyle()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetTextLineHeight() -> f32 {
    c_igGetTextLineHeight()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetTextLineHeightWithSpacing() -> f32 {
    c_igGetTextLineHeightWithSpacing()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetTime() -> c_double {
    c_igGetTime()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetTreeNodeToLabelSpacing() -> f32 {
    c_igGetTreeNodeToLabelSpacing()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetVersion() -> *const c_char {
    c_igGetVersion()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetWindowContentRegionMax() -> ImVec2 {
    c_igGetWindowContentRegionMax()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetWindowContentRegionMin() -> ImVec2 {
    c_igGetWindowContentRegionMin()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetWindowDockID() -> c_uint {
    c_igGetWindowDockID()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetWindowDpiScale() -> f32 {
    c_igGetWindowDpiScale()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetWindowDrawList() -> *mut c_void {
    c_igGetWindowDrawList()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetWindowHeight() -> f32 {
    c_igGetWindowHeight()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetWindowPos() -> ImVec2 {
    c_igGetWindowPos()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetWindowSize() -> ImVec2 {
    c_igGetWindowSize()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetWindowViewport() -> *mut c_void {
    c_igGetWindowViewport()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igGetWindowWidth() -> f32 {
    c_igGetWindowWidth()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIndent(arg0: f32) -> () {
    c_igIndent(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igInputDouble(arg0: *const c_char, arg1: *mut c_double, arg2: c_double, arg3: c_double, arg4: *const c_char, arg5: c_int) -> bool {
    c_igInputDouble(arg0, arg1, arg2, arg3, arg4, arg5)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igInputFloat(arg0: *const c_char, arg1: *mut f32, arg2: f32, arg3: f32, arg4: *const c_char, arg5: c_int) -> bool {
    c_igInputFloat(arg0, arg1, arg2, arg3, arg4, arg5)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igInputFloat3(arg0: *const c_char, arg1: *mut f32, arg2: *const c_char, arg3: c_int) -> bool {
    c_igInputFloat3(arg0, arg1, arg2, arg3)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igInputFloat4(arg0: *const c_char, arg1: *mut f32, arg2: *const c_char, arg3: c_int) -> bool {
    c_igInputFloat4(arg0, arg1, arg2, arg3)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igInputInt(arg0: *const c_char, arg1: *mut c_int, arg2: c_int, arg3: c_int, arg4: c_int) -> bool {
    c_igInputInt(arg0, arg1, arg2, arg3, arg4)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igInputText(arg0: *const c_char, arg1: *mut c_char, arg2: usize, arg3: c_int, arg4: *mut c_void, arg5: *mut c_void) -> bool {
    c_igInputText(arg0, arg1, arg2, arg3, arg4, arg5)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igInputTextMultiline(arg0: *const c_char, arg1: *mut c_char, arg2: usize, arg3: ImVec2, arg4: c_int, arg5: *mut c_void, arg6: *mut c_void) -> bool {
    c_igInputTextMultiline(arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igInputTextWithHint(arg0: *const c_char, arg1: *const c_char, arg2: *mut c_char, arg3: usize, arg4: c_int, arg5: *mut c_void, arg6: *mut c_void) -> bool {
    c_igInputTextWithHint(arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igInvisibleButton(arg0: *const c_char, arg1: ImVec2, arg2: c_int) -> bool {
    c_igInvisibleButton(arg0, arg1, arg2)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsAnyItemActive() -> bool {
    c_igIsAnyItemActive()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsAnyItemFocused() -> bool {
    c_igIsAnyItemFocused()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsAnyItemHovered() -> bool {
    c_igIsAnyItemHovered()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsAnyMouseDown() -> bool {
    c_igIsAnyMouseDown()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsItemActivated() -> bool {
    c_igIsItemActivated()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsItemActive() -> bool {
    c_igIsItemActive()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsItemClicked(arg0: c_int) -> bool {
    c_igIsItemClicked(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsItemDeactivated() -> bool {
    c_igIsItemDeactivated()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsItemDeactivatedAfterEdit() -> bool {
    c_igIsItemDeactivatedAfterEdit()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsItemEdited() -> bool {
    c_igIsItemEdited()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsItemFocused() -> bool {
    c_igIsItemFocused()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsItemHovered(arg0: c_int) -> bool {
    c_igIsItemHovered(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsItemToggledOpen() -> bool {
    c_igIsItemToggledOpen()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsItemToggledSelection() -> bool {
    c_igIsItemToggledSelection()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsItemVisible() -> bool {
    c_igIsItemVisible()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsKeyDown(arg0: c_int) -> bool {
    c_igIsKeyDown(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsKeyPressed(arg0: c_int, arg1: bool) -> bool {
    c_igIsKeyPressed(arg0, arg1)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsKeyReleased(arg0: c_int) -> bool {
    c_igIsKeyReleased(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsMouseClicked(arg0: c_int, arg1: bool) -> bool {
    c_igIsMouseClicked(arg0, arg1)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsMouseDoubleClicked(arg0: c_int) -> bool {
    c_igIsMouseDoubleClicked(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsMouseDown(arg0: c_int) -> bool {
    c_igIsMouseDown(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsMouseDragging(arg0: c_int, arg1: f32) -> bool {
    c_igIsMouseDragging(arg0, arg1)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsMouseHoveringRect(arg0: ImVec2, arg1: ImVec2, arg2: bool) -> bool {
    c_igIsMouseHoveringRect(arg0, arg1, arg2)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsMousePosValid(arg0: *const c_void) -> bool {
    c_igIsMousePosValid(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsMouseReleased(arg0: c_int) -> bool {
    c_igIsMouseReleased(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsMouseReleasedWithDelay(arg0: c_int, arg1: f32) -> bool {
    c_igIsMouseReleasedWithDelay(arg0, arg1)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsPopupOpen(arg0: *const c_char, arg1: c_int) -> bool {
    c_igIsPopupOpen(arg0, arg1)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsRectVisible(arg0: ImVec2, arg1: ImVec2) -> bool {
    c_igIsRectVisible(arg0, arg1)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsRectVisibleBySize(arg0: ImVec2) -> bool {
    c_igIsRectVisibleBySize(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsWindowAppearing() -> bool {
    c_igIsWindowAppearing()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsWindowCollapsed() -> bool {
    c_igIsWindowCollapsed()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsWindowDocked() -> bool {
    c_igIsWindowDocked()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsWindowFocused(arg0: c_int) -> bool {
    c_igIsWindowFocused(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igIsWindowHovered(arg0: c_int) -> bool {
    c_igIsWindowHovered(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igListBox(arg0: *const c_char, arg1: *mut c_int, arg2: *const *const c_char, arg3: c_int, arg4: c_int) -> bool {
    c_igListBox(arg0, arg1, arg2, arg3, arg4)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igLoadIniSettingsFromDisk(arg0: *const c_char) -> () {
    c_igLoadIniSettingsFromDisk(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igLoadIniSettingsFromMemory(arg0: *const c_char, arg1: usize) -> () {
    c_igLoadIniSettingsFromMemory(arg0, arg1);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igLogButtons() -> () {
    c_igLogButtons();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igLogFinish() -> () {
    c_igLogFinish();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igLogToClipboard(arg0: c_int) -> () {
    c_igLogToClipboard(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igLogToFile(arg0: c_int, arg1: *const c_char) -> () {
    c_igLogToFile(arg0, arg1);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igLogToTTY(arg0: c_int) -> () {
    c_igLogToTTY(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igMemAlloc(arg0: usize) -> *mut c_void {
    c_igMemAlloc(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igMemFree(arg0: *mut c_void) -> () {
    c_igMemFree(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igMenuItem(arg0: *const c_char, arg1: *const c_char, arg2: bool, arg3: bool) -> bool {
    c_igMenuItem(arg0, arg1, arg2, arg3)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igMenuItemBoolPtr(arg0: *const c_char, arg1: *const c_char, arg2: *mut bool, arg3: bool) -> bool {
    c_igMenuItemBoolPtr(arg0, arg1, arg2, arg3)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igNewFrame() -> () {
    c_igNewFrame();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igNewLine() -> () {
    c_igNewLine();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igNextColumn() -> () {
    c_igNextColumn();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igOpenPopup(arg0: *const c_char, arg1: c_int) -> () {
    c_igOpenPopup(arg0, arg1);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igOpenPopupID(arg0: c_uint, arg1: c_int) -> () {
    c_igOpenPopupID(arg0, arg1);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igOpenPopupOnItemClick(arg0: *const c_char, arg1: c_int) -> () {
    c_igOpenPopupOnItemClick(arg0, arg1);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igPlotHistogram(arg0: *const c_char, arg1: *const f32, arg2: c_int, arg3: c_int, arg4: *const c_char, arg5: f32, arg6: f32, arg7: ImVec2, arg8: c_int) -> () {
    c_igPlotHistogram(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igPlotLines(arg0: *const c_char, arg1: *const f32, arg2: c_int, arg3: c_int, arg4: *const c_char, arg5: f32, arg6: f32, arg7: ImVec2, arg8: c_int) -> () {
    c_igPlotLines(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igPopButtonRepeat() -> () {
    c_igPopButtonRepeat();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igPopClipRect() -> () {
    c_igPopClipRect();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igPopFont() -> () {
    c_igPopFont();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igPopID() -> () {
    c_igPopID();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igPopItemFlag() -> () {
    c_igPopItemFlag();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igPopItemWidth() -> () {
    c_igPopItemWidth();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igPopStyleColor(arg0: c_int) -> () {
    c_igPopStyleColor(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igPopStyleVar(arg0: c_int) -> () {
    c_igPopStyleVar(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igPopTabStop() -> () {
    c_igPopTabStop();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igPopTextWrapPos() -> () {
    c_igPopTextWrapPos();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igProgressBar(arg0: f32, arg1: ImVec2, arg2: *const c_char) -> () {
    c_igProgressBar(arg0, arg1, arg2);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igPushButtonRepeat(arg0: bool) -> () {
    c_igPushButtonRepeat(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igPushClipRect(arg0: ImVec2, arg1: ImVec2, arg2: bool) -> () {
    c_igPushClipRect(arg0, arg1, arg2);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igPushFont(arg0: *mut c_void) -> () {
    c_igPushFont(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igPushFontFloat(arg0: *mut c_void, arg1: f32) -> () {
    c_igPushFontFloat(arg0, arg1);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igPushID(arg0: *const c_char) -> () {
    c_igPushID(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igPushIDInt(arg0: c_int) -> () {
    c_igPushIDInt(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igPushIDPtr(arg0: *const c_void) -> () {
    c_igPushIDPtr(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igPushIDStr(arg0: *const c_char, arg1: *const c_char) -> () {
    c_igPushIDStr(arg0, arg1);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igPushItemFlag(arg0: c_int, arg1: bool) -> () {
    c_igPushItemFlag(arg0, arg1);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igPushItemWidth(arg0: f32) -> () {
    c_igPushItemWidth(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igPushTabStop(arg0: bool) -> () {
    c_igPushTabStop(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igPushTextWrapPos(arg0: f32) -> () {
    c_igPushTextWrapPos(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igRadioButton(arg0: *const c_char, arg1: bool) -> bool {
    c_igRadioButton(arg0, arg1)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igRadioButtonIntPtr(arg0: *const c_char, arg1: *mut c_int, arg2: c_int) -> bool {
    c_igRadioButtonIntPtr(arg0, arg1, arg2)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igRender() -> () {
    c_igRender();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igRenderPlatformWindowsDefault(arg0: *mut c_void, arg1: *mut c_void) -> () {
    c_igRenderPlatformWindowsDefault(arg0, arg1);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igResetMouseDragDelta(arg0: c_int) -> () {
    c_igResetMouseDragDelta(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSameLine(arg0: f32, arg1: f32) -> () {
    c_igSameLine(arg0, arg1);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSaveIniSettingsToDisk(arg0: *const c_char) -> () {
    c_igSaveIniSettingsToDisk(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSaveIniSettingsToMemory(arg0: *mut usize) -> *const c_char {
    c_igSaveIniSettingsToMemory(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSelectable(arg0: *const c_char, arg1: bool, arg2: c_int, arg3: ImVec2) -> bool {
    c_igSelectable(arg0, arg1, arg2, arg3)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSelectableBoolPtr(arg0: *const c_char, arg1: *mut bool, arg2: c_int, arg3: ImVec2) -> bool {
    c_igSelectableBoolPtr(arg0, arg1, arg2, arg3)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSeparator() -> () {
    c_igSeparator();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSeparatorText(arg0: *const c_char) -> () {
    c_igSeparatorText(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetClipboardText(arg0: *const c_char) -> () {
    c_igSetClipboardText(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetColorEditOptions(arg0: c_int) -> () {
    c_igSetColorEditOptions(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetColumnOffset(arg0: c_int, arg1: f32) -> () {
    c_igSetColumnOffset(arg0, arg1);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetColumnWidth(arg0: c_int, arg1: f32) -> () {
    c_igSetColumnWidth(arg0, arg1);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetCurrentContext(arg0: *mut c_void) -> () {
    c_igSetCurrentContext(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetCursorPos(arg0: ImVec2) -> () {
    c_igSetCursorPos(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetCursorPosX(arg0: f32) -> () {
    c_igSetCursorPosX(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetCursorPosY(arg0: f32) -> () {
    c_igSetCursorPosY(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetCursorScreenPos(arg0: ImVec2) -> () {
    c_igSetCursorScreenPos(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetItemDefaultFocus() -> () {
    c_igSetItemDefaultFocus();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetItemKeyOwner(arg0: c_int) -> bool {
    c_igSetItemKeyOwner(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetKeyboardFocusHere(arg0: c_int) -> () {
    c_igSetKeyboardFocusHere(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetMouseCursor(arg0: c_int) -> () {
    c_igSetMouseCursor(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetNavCursorVisible(arg0: bool) -> () {
    c_igSetNavCursorVisible(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetNextFrameWantCaptureKeyboard(arg0: bool) -> () {
    c_igSetNextFrameWantCaptureKeyboard(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetNextFrameWantCaptureMouse(arg0: bool) -> () {
    c_igSetNextFrameWantCaptureMouse(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetNextItemAllowOverlap() -> () {
    c_igSetNextItemAllowOverlap();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetNextItemStorageID(arg0: c_uint) -> () {
    c_igSetNextItemStorageID(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetNextItemWidth(arg0: f32) -> () {
    c_igSetNextItemWidth(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetNextWindowBgAlpha(arg0: f32) -> () {
    c_igSetNextWindowBgAlpha(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetNextWindowClass(arg0: *const c_void) -> () {
    c_igSetNextWindowClass(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetNextWindowContentSize(arg0: ImVec2) -> () {
    c_igSetNextWindowContentSize(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetNextWindowFocus() -> () {
    c_igSetNextWindowFocus();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetNextWindowScroll(arg0: ImVec2) -> () {
    c_igSetNextWindowScroll(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetNextWindowSizeConstraints(arg0: ImVec2, arg1: ImVec2, arg2: *mut c_void, arg3: *mut c_void) -> () {
    c_igSetNextWindowSizeConstraints(arg0, arg1, arg2, arg3);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetNextWindowViewport(arg0: c_uint) -> () {
    c_igSetNextWindowViewport(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetScrollFromPosX(arg0: f32, arg1: f32) -> () {
    c_igSetScrollFromPosX(arg0, arg1);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetScrollFromPosY(arg0: f32, arg1: f32) -> () {
    c_igSetScrollFromPosY(arg0, arg1);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetScrollHereX(arg0: f32) -> () {
    c_igSetScrollHereX(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetScrollHereY(arg0: f32) -> () {
    c_igSetScrollHereY(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetScrollX(arg0: f32) -> () {
    c_igSetScrollX(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetScrollY(arg0: f32) -> () {
    c_igSetScrollY(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetStateStorage(arg0: *mut c_void) -> () {
    c_igSetStateStorage(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetTabItemClosed(arg0: *const c_char) -> () {
    c_igSetTabItemClosed(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetWindowFocus() -> () {
    c_igSetWindowFocus();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetWindowFocusStr(arg0: *const c_char) -> () {
    c_igSetWindowFocusStr(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSetWindowFontScale(arg0: f32) -> () {
    c_igSetWindowFontScale(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igShowAboutWindow(arg0: *mut bool) -> () {
    c_igShowAboutWindow(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igShowDebugLogWindow(arg0: *mut bool) -> () {
    c_igShowDebugLogWindow(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igShowDemoWindow(arg0: *mut bool) -> () {
    c_igShowDemoWindow(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igShowFontSelector(arg0: *const c_char) -> () {
    c_igShowFontSelector(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igShowIDStackToolWindow(arg0: *mut bool) -> () {
    c_igShowIDStackToolWindow(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igShowMetricsWindow(arg0: *mut bool) -> () {
    c_igShowMetricsWindow(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igShowStyleEditor(arg0: *mut c_void) -> () {
    c_igShowStyleEditor(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igShowStyleSelector(arg0: *const c_char) -> bool {
    c_igShowStyleSelector(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igShowUserGuide() -> () {
    c_igShowUserGuide();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSliderAngle(arg0: *const c_char, arg1: *mut f32, arg2: f32, arg3: f32, arg4: *const c_char, arg5: c_int) -> bool {
    c_igSliderAngle(arg0, arg1, arg2, arg3, arg4, arg5)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSliderFloat(arg0: *const c_char, arg1: *mut f32, arg2: f32, arg3: f32, arg4: *const c_char, arg5: c_int) -> bool {
    c_igSliderFloat(arg0, arg1, arg2, arg3, arg4, arg5)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSliderFloat3(arg0: *const c_char, arg1: *mut f32, arg2: f32, arg3: f32, arg4: *const c_char, arg5: c_int) -> bool {
    c_igSliderFloat3(arg0, arg1, arg2, arg3, arg4, arg5)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSliderFloat4(arg0: *const c_char, arg1: *mut f32, arg2: f32, arg3: f32, arg4: *const c_char, arg5: c_int) -> bool {
    c_igSliderFloat4(arg0, arg1, arg2, arg3, arg4, arg5)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSliderInt(arg0: *const c_char, arg1: *mut c_int, arg2: c_int, arg3: c_int, arg4: *const c_char, arg5: c_int) -> bool {
    c_igSliderInt(arg0, arg1, arg2, arg3, arg4, arg5)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSmallButton(arg0: *const c_char) -> bool {
    c_igSmallButton(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igSpacing() -> () {
    c_igSpacing();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igStyleColorsClassic(arg0: *mut c_void) -> () {
    c_igStyleColorsClassic(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igStyleColorsDark(arg0: *mut c_void) -> () {
    c_igStyleColorsDark(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igStyleColorsLight(arg0: *mut c_void) -> () {
    c_igStyleColorsLight(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igTabItemButton(arg0: *const c_char, arg1: c_int) -> bool {
    c_igTabItemButton(arg0, arg1)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igTableAngledHeadersRow() -> () {
    c_igTableAngledHeadersRow();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igTableGetColumnCount() -> c_int {
    c_igTableGetColumnCount()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igTableGetColumnFlags(arg0: c_int) -> c_int {
    c_igTableGetColumnFlags(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igTableGetColumnIndex() -> c_int {
    c_igTableGetColumnIndex()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igTableGetColumnName(arg0: c_int) -> *const c_char {
    c_igTableGetColumnName(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igTableGetHoveredColumn() -> c_int {
    c_igTableGetHoveredColumn()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igTableGetRowIndex() -> c_int {
    c_igTableGetRowIndex()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igTableGetSortSpecs() -> *mut c_void {
    c_igTableGetSortSpecs()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igTableHeader(arg0: *const c_char) -> () {
    c_igTableHeader(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igTableHeadersRow() -> () {
    c_igTableHeadersRow();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igTableNextColumn() -> bool {
    c_igTableNextColumn()
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igTableNextRow(arg0: c_int, arg1: f32) -> () {
    c_igTableNextRow(arg0, arg1);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igTableSetColumnEnabled(arg0: c_int, arg1: bool) -> () {
    c_igTableSetColumnEnabled(arg0, arg1);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igTableSetColumnIndex(arg0: c_int) -> bool {
    c_igTableSetColumnIndex(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igTableSetupColumn(arg0: *const c_char, arg1: c_int, arg2: f32, arg3: c_uint) -> () {
    c_igTableSetupColumn(arg0, arg1, arg2, arg3);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igTableSetupScrollFreeze(arg0: c_int, arg1: c_int) -> () {
    c_igTableSetupScrollFreeze(arg0, arg1);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igTextLink(arg0: *const c_char) -> bool {
    c_igTextLink(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igTextLinkOpenURL(arg0: *const c_char, arg1: *const c_char) -> bool {
    c_igTextLinkOpenURL(arg0, arg1)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igTextUnformatted(arg0: *const c_char, arg1: *const c_char) -> () {
    c_igTextUnformatted(arg0, arg1);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igTreeNode(arg0: *const c_char) -> bool {
    c_igTreeNode(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igTreeNodeEx(arg0: *const c_char, arg1: c_int) -> bool {
    c_igTreeNodeEx(arg0, arg1)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igTreeNodeGetOpen(arg0: c_uint) -> bool {
    c_igTreeNodeGetOpen(arg0)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igTreePop() -> () {
    c_igTreePop();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igTreePush(arg0: *const c_char) -> () {
    c_igTreePush(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igTreePushPtr(arg0: *const c_void) -> () {
    c_igTreePushPtr(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igUnindent(arg0: f32) -> () {
    c_igUnindent(arg0);
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igUpdatePlatformWindows() -> () {
    c_igUpdatePlatformWindows();
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igVSliderFloat(arg0: *const c_char, arg1: ImVec2, arg2: *mut f32, arg3: f32, arg4: f32, arg5: *const c_char, arg6: c_int) -> bool {
    c_igVSliderFloat(arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

#[no_mangle]
pub unsafe extern "C" fn imgui_wasm_igVSliderInt(arg0: *const c_char, arg1: ImVec2, arg2: *mut c_int, arg3: c_int, arg4: c_int, arg5: *const c_char, arg6: c_int) -> bool {
    c_igVSliderInt(arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}
