[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "imgui_wasm"
version = "0.1.0"
description = "Python bindings for ImGuiWasm"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
dependencies = []

[project.urls]
Homepage = "https://github.com/n3in2019/imgui_wasm"
Repository = "https://github.com/n3in2019/imgui_wasm"
Issues = "https://github.com/n3in2019/imgui_wasm/issues"

[tool.setuptools.packages.find]
where = ["."]
include = ["imgui_wasm*"]
