// This file is generated by imgui_ws/tools/generate_bindings.py. Do not edit.
//
// ImGuiWasm call-stream capture surface (host-facing).
//
// Applications keep using the original ImGui::<Widget> API. The public
// imgui_wasm.hpp header redirects that namespace spelling to this capture
// surface after all library declarations have been parsed.
//
// When call-stream transport is OFF, capture is a no-op and these wrappers
// are zero-cost forwards to ImGui::.
#pragma once

#include "imgui.h"
#include "imgui_wasm_opcodes.h"
#include "imgui_wasm_capture.h"

namespace imgui_wasm {

// Queries and unsupported calls retain their native ImGui implementation.
using namespace ImGui;

    inline const ImGuiPayload* AcceptDragDropPayload(const char* type, ImGuiDragDropFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_ACCEPT_DRAG_DROP_PAYLOAD);
        imgui_wasm_capture_string(type);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::AcceptDragDropPayload(type, flags);
    }

    inline void AlignTextToFramePadding() {
        imgui_wasm_capture_begin(OP_IG_ALIGN_TEXT_TO_FRAME_PADDING);
        imgui_wasm_capture_end();
        ImGui::AlignTextToFramePadding();
    }

    inline bool ArrowButton(const char* str_id, ImGuiDir dir) {
        imgui_wasm_capture_begin(OP_IG_ARROW_BUTTON);
        imgui_wasm_capture_string(str_id);
        imgui_wasm_capture_u32((unsigned)(dir));
        imgui_wasm_capture_end();
        return ImGui::ArrowButton(str_id, dir);
    }

    inline bool Begin(const char* name, bool* p_open = nullptr, ImGuiWindowFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_BEGIN);
        imgui_wasm_capture_string(name);
        imgui_wasm_capture_ptr((const void*)(p_open), 1u);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::Begin(name, p_open, flags);
    }

    inline bool BeginChild(unsigned int id, const ImVec2& size = ImVec2(0, 0), ImGuiChildFlags child_flags = 0, ImGuiWindowFlags window_flags = 0) {
        imgui_wasm_capture_begin(OP_IG_BEGIN_CHILD_ID);
        imgui_wasm_capture_u32((unsigned long long)(id));
        imgui_wasm_capture_vec2(size.x, size.y);
        imgui_wasm_capture_u32((unsigned)(child_flags));
        imgui_wasm_capture_u32((unsigned)(window_flags));
        imgui_wasm_capture_end();
        return ImGui::BeginChild(id, size, child_flags, window_flags);
    }

    inline bool BeginChild(const char* str_id, const ImVec2& size = ImVec2(0, 0), ImGuiChildFlags child_flags = 0, ImGuiWindowFlags window_flags = 0) {
        imgui_wasm_capture_begin(OP_IG_BEGIN_CHILD);
        imgui_wasm_capture_string(str_id);
        imgui_wasm_capture_vec2(size.x, size.y);
        imgui_wasm_capture_u32((unsigned)(child_flags));
        imgui_wasm_capture_u32((unsigned)(window_flags));
        imgui_wasm_capture_end();
        return ImGui::BeginChild(str_id, size, child_flags, window_flags);
    }

    inline bool BeginCombo(const char* label, const char* preview_value, ImGuiComboFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_BEGIN_COMBO);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_string(preview_value);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::BeginCombo(label, preview_value, flags);
    }

    inline void BeginDisabled(bool disabled = true) {
        imgui_wasm_capture_begin(OP_IG_BEGIN_DISABLED);
        imgui_wasm_capture_u8((unsigned long long)(disabled));
        imgui_wasm_capture_end();
        ImGui::BeginDisabled(disabled);
    }

    inline bool BeginDragDropSource(ImGuiDragDropFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_BEGIN_DRAG_DROP_SOURCE);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::BeginDragDropSource(flags);
    }

    inline bool BeginDragDropTarget() {
        imgui_wasm_capture_begin(OP_IG_BEGIN_DRAG_DROP_TARGET);
        imgui_wasm_capture_end();
        return ImGui::BeginDragDropTarget();
    }

    inline void BeginGroup() {
        imgui_wasm_capture_begin(OP_IG_BEGIN_GROUP);
        imgui_wasm_capture_end();
        ImGui::BeginGroup();
    }

    inline bool BeginItemTooltip() {
        imgui_wasm_capture_begin(OP_IG_BEGIN_ITEM_TOOLTIP);
        imgui_wasm_capture_end();
        return ImGui::BeginItemTooltip();
    }

    inline bool BeginListBox(const char* label, const ImVec2& size = ImVec2(0, 0)) {
        imgui_wasm_capture_begin(OP_IG_BEGIN_LIST_BOX);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_vec2(size.x, size.y);
        imgui_wasm_capture_end();
        return ImGui::BeginListBox(label, size);
    }

    inline bool BeginMainMenuBar() {
        imgui_wasm_capture_begin(OP_IG_BEGIN_MAIN_MENU_BAR);
        imgui_wasm_capture_end();
        return ImGui::BeginMainMenuBar();
    }

    inline bool BeginMenu(const char* label, bool enabled = true) {
        imgui_wasm_capture_begin(OP_IG_BEGIN_MENU);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_u8((unsigned long long)(enabled));
        imgui_wasm_capture_end();
        return ImGui::BeginMenu(label, enabled);
    }

    inline bool BeginMenuBar() {
        imgui_wasm_capture_begin(OP_IG_BEGIN_MENU_BAR);
        imgui_wasm_capture_end();
        return ImGui::BeginMenuBar();
    }

    inline ImGuiMultiSelectIO* BeginMultiSelect(ImGuiMultiSelectFlags flags, int selection_size = -1, int items_count = -1) {
        imgui_wasm_capture_begin(OP_IG_BEGIN_MULTI_SELECT);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_u32((unsigned long long)(selection_size));
        imgui_wasm_capture_u32((unsigned long long)(items_count));
        imgui_wasm_capture_end();
        return ImGui::BeginMultiSelect(flags, selection_size, items_count);
    }

    inline bool BeginPopup(const char* str_id, ImGuiWindowFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_BEGIN_POPUP);
        imgui_wasm_capture_string(str_id);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::BeginPopup(str_id, flags);
    }

    inline bool BeginPopupContextItem(const char* str_id = nullptr, ImGuiPopupFlags popup_flags = 0) {
        imgui_wasm_capture_begin(OP_IG_BEGIN_POPUP_CONTEXT_ITEM);
        imgui_wasm_capture_string(str_id);
        imgui_wasm_capture_u32((unsigned)(popup_flags));
        imgui_wasm_capture_end();
        return ImGui::BeginPopupContextItem(str_id, popup_flags);
    }

    inline bool BeginPopupContextVoid(const char* str_id = nullptr, ImGuiPopupFlags popup_flags = 0) {
        imgui_wasm_capture_begin(OP_IG_BEGIN_POPUP_CONTEXT_VOID);
        imgui_wasm_capture_string(str_id);
        imgui_wasm_capture_u32((unsigned)(popup_flags));
        imgui_wasm_capture_end();
        return ImGui::BeginPopupContextVoid(str_id, popup_flags);
    }

    inline bool BeginPopupContextWindow(const char* str_id = nullptr, ImGuiPopupFlags popup_flags = 0) {
        imgui_wasm_capture_begin(OP_IG_BEGIN_POPUP_CONTEXT_WINDOW);
        imgui_wasm_capture_string(str_id);
        imgui_wasm_capture_u32((unsigned)(popup_flags));
        imgui_wasm_capture_end();
        return ImGui::BeginPopupContextWindow(str_id, popup_flags);
    }

    inline bool BeginPopupModal(const char* name, bool* p_open = nullptr, ImGuiWindowFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_BEGIN_POPUP_MODAL);
        imgui_wasm_capture_string(name);
        imgui_wasm_capture_ptr((const void*)(p_open), 1u);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::BeginPopupModal(name, p_open, flags);
    }

    inline bool BeginTabBar(const char* str_id, ImGuiTabBarFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_BEGIN_TAB_BAR);
        imgui_wasm_capture_string(str_id);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::BeginTabBar(str_id, flags);
    }

    inline bool BeginTabItem(const char* label, bool* p_open = nullptr, ImGuiTabItemFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_BEGIN_TAB_ITEM);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_ptr((const void*)(p_open), 1u);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::BeginTabItem(label, p_open, flags);
    }

    inline bool BeginTable(const char* str_id, int columns, ImGuiTableFlags flags = 0, const ImVec2& outer_size = ImVec2(0.0f, 0.0f), float inner_width = 0.0f) {
        imgui_wasm_capture_begin(OP_IG_BEGIN_TABLE);
        imgui_wasm_capture_string(str_id);
        imgui_wasm_capture_u32((unsigned long long)(columns));
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_vec2(outer_size.x, outer_size.y);
        imgui_wasm_capture_ptr((const void*)(&inner_width), 4u);
        imgui_wasm_capture_end();
        return ImGui::BeginTable(str_id, columns, flags, outer_size, inner_width);
    }

    inline bool BeginTooltip() {
        imgui_wasm_capture_begin(OP_IG_BEGIN_TOOLTIP);
        imgui_wasm_capture_end();
        return ImGui::BeginTooltip();
    }

    inline void Bullet() {
        imgui_wasm_capture_begin(OP_IG_BULLET);
        imgui_wasm_capture_end();
        ImGui::Bullet();
    }

    inline bool Button(const char* label, const ImVec2& size = ImVec2(0, 0)) {
        imgui_wasm_capture_begin(OP_IG_BUTTON);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_vec2(size.x, size.y);
        imgui_wasm_capture_end();
        return ImGui::Button(label, size);
    }

    inline bool Checkbox(const char* label, bool* v) {
        imgui_wasm_capture_begin(OP_IG_CHECKBOX);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_ptr((const void*)(v), 1u);
        imgui_wasm_capture_end();
        return ImGui::Checkbox(label, v);
    }

    inline bool CheckboxFlags(const char* label, int* flags, int flags_value) {
        imgui_wasm_capture_begin(OP_IG_CHECKBOX_FLAGS_INT_PTR);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_ptr((const void*)(flags), 4u);
        imgui_wasm_capture_u32((unsigned long long)(flags_value));
        imgui_wasm_capture_end();
        return ImGui::CheckboxFlags(label, flags, flags_value);
    }

    inline bool CheckboxFlags(const char* label, unsigned int* flags, unsigned int flags_value) {
        imgui_wasm_capture_begin(OP_IG_CHECKBOX_FLAGS_UINT_PTR);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_ptr((const void*)(flags), 4u);
        imgui_wasm_capture_u32((unsigned long long)(flags_value));
        imgui_wasm_capture_end();
        return ImGui::CheckboxFlags(label, flags, flags_value);
    }

    inline void CloseCurrentPopup() {
        imgui_wasm_capture_begin(OP_IG_CLOSE_CURRENT_POPUP);
        imgui_wasm_capture_end();
        ImGui::CloseCurrentPopup();
    }

    inline bool CollapsingHeader(const char* label, bool* p_visible, ImGuiTreeNodeFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_COLLAPSING_HEADER_BOOL_PTR);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_ptr((const void*)(p_visible), 1u);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::CollapsingHeader(label, p_visible, flags);
    }

    inline bool CollapsingHeader(const char* label, ImGuiTreeNodeFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_COLLAPSING_HEADER);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::CollapsingHeader(label, flags);
    }

    inline bool ColorButton(const char* desc_id, const ImVec4& col, ImGuiColorEditFlags flags = 0, const ImVec2& size = ImVec2(0, 0)) {
        imgui_wasm_capture_begin(OP_IG_COLOR_BUTTON);
        imgui_wasm_capture_string(desc_id);
        imgui_wasm_capture_vec4(col.x, col.y, col.z, col.w);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_vec2(size.x, size.y);
        imgui_wasm_capture_end();
        return ImGui::ColorButton(desc_id, col, flags, size);
    }

    inline bool ColorEdit3(const char* label, float* col, ImGuiColorEditFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_COLOR_EDIT_3);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_floats(col, 3);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::ColorEdit3(label, col, flags);
    }

    inline bool ColorEdit4(const char* label, float* col, ImGuiColorEditFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_COLOR_EDIT_4);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_floats(col, 4);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::ColorEdit4(label, col, flags);
    }

    inline bool ColorPicker3(const char* label, float* col, ImGuiColorEditFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_COLOR_PICKER_3);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_floats(col, 3);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::ColorPicker3(label, col, flags);
    }

    inline void Columns(int count = 1, const char* id = nullptr, bool borders = true) {
        imgui_wasm_capture_begin(OP_IG_COLUMNS);
        imgui_wasm_capture_u32((unsigned long long)(count));
        imgui_wasm_capture_string(id);
        imgui_wasm_capture_u8((unsigned long long)(borders));
        imgui_wasm_capture_end();
        ImGui::Columns(count, id, borders);
    }

    inline bool Combo(const char* label, int* current_item, const char* items_separated_by_zeros, int popup_max_height_in_items = -1) {
        imgui_wasm_capture_begin(OP_IG_COMBO);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_ptr((const void*)(current_item), 4u);
        imgui_wasm_capture_string(items_separated_by_zeros);
        imgui_wasm_capture_u32((unsigned long long)(popup_max_height_in_items));
        imgui_wasm_capture_end();
        return ImGui::Combo(label, current_item, items_separated_by_zeros, popup_max_height_in_items);
    }

    inline bool Combo(const char* label, int* current_item, const char* const* items, int items_count, int popup_max_height_in_items = -1) {
        imgui_wasm_capture_begin(OP_IG_COMBO_CHAR);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_ptr((const void*)(current_item), 4u);
        imgui_wasm_capture_u32((unsigned)(items_count));
        imgui_wasm_capture_strings_n(items, (unsigned)(items_count));
        imgui_wasm_capture_u32((unsigned long long)(items_count));
        imgui_wasm_capture_u32((unsigned long long)(popup_max_height_in_items));
        imgui_wasm_capture_end();
        return ImGui::Combo(label, current_item, items, items_count, popup_max_height_in_items);
    }

    inline bool DebugCheckVersionAndDataLayout(const char* version_str, unsigned int sz_io, unsigned int sz_style, unsigned int sz_vec2, unsigned int sz_vec4, unsigned int sz_drawvert, unsigned int sz_drawidx) {
        imgui_wasm_capture_begin(OP_IG_DEBUG_CHECK_VERSION_AND_DATA_LAYOUT);
        imgui_wasm_capture_string(version_str);
        imgui_wasm_capture_u32((unsigned long long)(sz_io));
        imgui_wasm_capture_u32((unsigned long long)(sz_style));
        imgui_wasm_capture_u32((unsigned long long)(sz_vec2));
        imgui_wasm_capture_u32((unsigned long long)(sz_vec4));
        imgui_wasm_capture_u32((unsigned long long)(sz_drawvert));
        imgui_wasm_capture_u32((unsigned long long)(sz_drawidx));
        imgui_wasm_capture_end();
        return ImGui::DebugCheckVersionAndDataLayout(version_str, sz_io, sz_style, sz_vec2, sz_vec4, sz_drawvert, sz_drawidx);
    }

    inline void DebugStartItemPicker() {
        imgui_wasm_capture_begin(OP_IG_DEBUG_START_ITEM_PICKER);
        imgui_wasm_capture_end();
        ImGui::DebugStartItemPicker();
    }

    inline void DebugTextEncoding(const char* text) {
        imgui_wasm_capture_begin(OP_IG_DEBUG_TEXT_ENCODING);
        imgui_wasm_capture_string(text);
        imgui_wasm_capture_end();
        ImGui::DebugTextEncoding(text);
    }

    inline void DestroyPlatformWindows() {
        imgui_wasm_capture_begin(OP_IG_DESTROY_PLATFORM_WINDOWS);
        imgui_wasm_capture_end();
        ImGui::DestroyPlatformWindows();
    }

    inline bool DragFloat(const char* label, float* v, float v_speed = 1.0f, float v_min = 0.0f, float v_max = 0.0f, const char* format = "%.3f", ImGuiSliderFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_DRAG_FLOAT);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_ptr((const void*)(v), 4u);
        imgui_wasm_capture_ptr((const void*)(&v_speed), 4u);
        imgui_wasm_capture_ptr((const void*)(&v_min), 4u);
        imgui_wasm_capture_ptr((const void*)(&v_max), 4u);
        imgui_wasm_capture_string(format);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::DragFloat(label, v, v_speed, v_min, v_max, format, flags);
    }

    inline bool DragFloat3(const char* label, float* v, float v_speed = 1.0f, float v_min = 0.0f, float v_max = 0.0f, const char* format = "%.3f", ImGuiSliderFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_DRAG_FLOAT_3);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_floats(v, 3);
        imgui_wasm_capture_ptr((const void*)(&v_speed), 4u);
        imgui_wasm_capture_ptr((const void*)(&v_min), 4u);
        imgui_wasm_capture_ptr((const void*)(&v_max), 4u);
        imgui_wasm_capture_string(format);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::DragFloat3(label, v, v_speed, v_min, v_max, format, flags);
    }

    inline bool DragFloat4(const char* label, float* v, float v_speed = 1.0f, float v_min = 0.0f, float v_max = 0.0f, const char* format = "%.3f", ImGuiSliderFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_DRAG_FLOAT_4);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_floats(v, 4);
        imgui_wasm_capture_ptr((const void*)(&v_speed), 4u);
        imgui_wasm_capture_ptr((const void*)(&v_min), 4u);
        imgui_wasm_capture_ptr((const void*)(&v_max), 4u);
        imgui_wasm_capture_string(format);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::DragFloat4(label, v, v_speed, v_min, v_max, format, flags);
    }

    inline bool DragFloatRange2(const char* label, float* v_current_min, float* v_current_max, float v_speed = 1.0f, float v_min = 0.0f, float v_max = 0.0f, const char* format = "%.3f", const char* format_max = nullptr, ImGuiSliderFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_DRAG_FLOAT_RANGE_2);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_ptr((const void*)(v_current_min), 4u);
        imgui_wasm_capture_ptr((const void*)(v_current_max), 4u);
        imgui_wasm_capture_ptr((const void*)(&v_speed), 4u);
        imgui_wasm_capture_ptr((const void*)(&v_min), 4u);
        imgui_wasm_capture_ptr((const void*)(&v_max), 4u);
        imgui_wasm_capture_string(format);
        imgui_wasm_capture_string(format_max);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::DragFloatRange2(label, v_current_min, v_current_max, v_speed, v_min, v_max, format, format_max, flags);
    }

    inline bool DragInt(const char* label, int* v, float v_speed = 1.0f, int v_min = 0, int v_max = 0, const char* format = "%d", ImGuiSliderFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_DRAG_INT);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_ptr((const void*)(v), 4u);
        imgui_wasm_capture_ptr((const void*)(&v_speed), 4u);
        imgui_wasm_capture_u32((unsigned long long)(v_min));
        imgui_wasm_capture_u32((unsigned long long)(v_max));
        imgui_wasm_capture_string(format);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::DragInt(label, v, v_speed, v_min, v_max, format, flags);
    }

    inline bool DragIntRange2(const char* label, int* v_current_min, int* v_current_max, float v_speed = 1.0f, int v_min = 0, int v_max = 0, const char* format = "%d", const char* format_max = nullptr, ImGuiSliderFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_DRAG_INT_RANGE_2);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_ptr((const void*)(v_current_min), 4u);
        imgui_wasm_capture_ptr((const void*)(v_current_max), 4u);
        imgui_wasm_capture_ptr((const void*)(&v_speed), 4u);
        imgui_wasm_capture_u32((unsigned long long)(v_min));
        imgui_wasm_capture_u32((unsigned long long)(v_max));
        imgui_wasm_capture_string(format);
        imgui_wasm_capture_string(format_max);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::DragIntRange2(label, v_current_min, v_current_max, v_speed, v_min, v_max, format, format_max, flags);
    }

    inline void Dummy(const ImVec2& size) {
        imgui_wasm_capture_begin(OP_IG_DUMMY);
        imgui_wasm_capture_vec2(size.x, size.y);
        imgui_wasm_capture_end();
        ImGui::Dummy(size);
    }

    inline void End() {
        imgui_wasm_capture_begin(OP_IG_END);
        imgui_wasm_capture_end();
        ImGui::End();
    }

    inline void EndChild() {
        imgui_wasm_capture_begin(OP_IG_END_CHILD);
        imgui_wasm_capture_end();
        ImGui::EndChild();
    }

    inline void EndCombo() {
        imgui_wasm_capture_begin(OP_IG_END_COMBO);
        imgui_wasm_capture_end();
        ImGui::EndCombo();
    }

    inline void EndDisabled() {
        imgui_wasm_capture_begin(OP_IG_END_DISABLED);
        imgui_wasm_capture_end();
        ImGui::EndDisabled();
    }

    inline void EndDragDropSource() {
        imgui_wasm_capture_begin(OP_IG_END_DRAG_DROP_SOURCE);
        imgui_wasm_capture_end();
        ImGui::EndDragDropSource();
    }

    inline void EndDragDropTarget() {
        imgui_wasm_capture_begin(OP_IG_END_DRAG_DROP_TARGET);
        imgui_wasm_capture_end();
        ImGui::EndDragDropTarget();
    }

    inline void EndFrame() {
        imgui_wasm_capture_begin(OP_IG_END_FRAME);
        imgui_wasm_capture_end();
        ImGui::EndFrame();
    }

    inline void EndGroup() {
        imgui_wasm_capture_begin(OP_IG_END_GROUP);
        imgui_wasm_capture_end();
        ImGui::EndGroup();
    }

    inline void EndListBox() {
        imgui_wasm_capture_begin(OP_IG_END_LIST_BOX);
        imgui_wasm_capture_end();
        ImGui::EndListBox();
    }

    inline void EndMainMenuBar() {
        imgui_wasm_capture_begin(OP_IG_END_MAIN_MENU_BAR);
        imgui_wasm_capture_end();
        ImGui::EndMainMenuBar();
    }

    inline void EndMenu() {
        imgui_wasm_capture_begin(OP_IG_END_MENU);
        imgui_wasm_capture_end();
        ImGui::EndMenu();
    }

    inline void EndMenuBar() {
        imgui_wasm_capture_begin(OP_IG_END_MENU_BAR);
        imgui_wasm_capture_end();
        ImGui::EndMenuBar();
    }

    inline ImGuiMultiSelectIO* EndMultiSelect() {
        imgui_wasm_capture_begin(OP_IG_END_MULTI_SELECT);
        imgui_wasm_capture_end();
        return ImGui::EndMultiSelect();
    }

    inline void EndPopup() {
        imgui_wasm_capture_begin(OP_IG_END_POPUP);
        imgui_wasm_capture_end();
        ImGui::EndPopup();
    }

    inline void EndTabBar() {
        imgui_wasm_capture_begin(OP_IG_END_TAB_BAR);
        imgui_wasm_capture_end();
        ImGui::EndTabBar();
    }

    inline void EndTabItem() {
        imgui_wasm_capture_begin(OP_IG_END_TAB_ITEM);
        imgui_wasm_capture_end();
        ImGui::EndTabItem();
    }

    inline void EndTable() {
        imgui_wasm_capture_begin(OP_IG_END_TABLE);
        imgui_wasm_capture_end();
        ImGui::EndTable();
    }

    inline void EndTooltip() {
        imgui_wasm_capture_begin(OP_IG_END_TOOLTIP);
        imgui_wasm_capture_end();
        ImGui::EndTooltip();
    }

    inline ImGuiViewport* FindViewportByID(unsigned int viewport_id) {
        imgui_wasm_capture_begin(OP_IG_FIND_VIEWPORT_BY_ID);
        imgui_wasm_capture_u32((unsigned long long)(viewport_id));
        imgui_wasm_capture_end();
        return ImGui::FindViewportByID(viewport_id);
    }

    inline void Indent(float indent_w = 0.0f) {
        imgui_wasm_capture_begin(OP_IG_INDENT);
        imgui_wasm_capture_ptr((const void*)(&indent_w), 4u);
        imgui_wasm_capture_end();
        ImGui::Indent(indent_w);
    }

    inline bool InputDouble(const char* label, double* v, double step = 0.0, double step_fast = 0.0, const char* format = "%.6f", ImGuiInputTextFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_INPUT_DOUBLE);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_ptr((const void*)(v), 8u);
        imgui_wasm_capture_ptr((const void*)(&step), 8u);
        imgui_wasm_capture_ptr((const void*)(&step_fast), 8u);
        imgui_wasm_capture_string(format);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::InputDouble(label, v, step, step_fast, format, flags);
    }

    inline bool InputFloat(const char* label, float* v, float step = 0.0f, float step_fast = 0.0f, const char* format = "%.3f", ImGuiInputTextFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_INPUT_FLOAT);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_ptr((const void*)(v), 4u);
        imgui_wasm_capture_ptr((const void*)(&step), 4u);
        imgui_wasm_capture_ptr((const void*)(&step_fast), 4u);
        imgui_wasm_capture_string(format);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::InputFloat(label, v, step, step_fast, format, flags);
    }

    inline bool InputFloat3(const char* label, float* v, const char* format = "%.3f", ImGuiInputTextFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_INPUT_FLOAT_3);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_floats(v, 3);
        imgui_wasm_capture_string(format);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::InputFloat3(label, v, format, flags);
    }

    inline bool InputFloat4(const char* label, float* v, const char* format = "%.3f", ImGuiInputTextFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_INPUT_FLOAT_4);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_floats(v, 4);
        imgui_wasm_capture_string(format);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::InputFloat4(label, v, format, flags);
    }

    inline bool InputInt(const char* label, int* v, int step = 1, int step_fast = 100, ImGuiInputTextFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_INPUT_INT);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_ptr((const void*)(v), 4u);
        imgui_wasm_capture_u32((unsigned long long)(step));
        imgui_wasm_capture_u32((unsigned long long)(step_fast));
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::InputInt(label, v, step, step_fast, flags);
    }

    inline bool InvisibleButton(const char* str_id, const ImVec2& size, ImGuiButtonFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_INVISIBLE_BUTTON);
        imgui_wasm_capture_string(str_id);
        imgui_wasm_capture_vec2(size.x, size.y);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::InvisibleButton(str_id, size, flags);
    }

    inline bool ListBox(const char* label, int* current_item, const char* const* items, int items_count, int height_in_items = -1) {
        imgui_wasm_capture_begin(OP_IG_LIST_BOX);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_ptr((const void*)(current_item), 4u);
        imgui_wasm_capture_u32((unsigned)(items_count));
        imgui_wasm_capture_strings_n(items, (unsigned)(items_count));
        imgui_wasm_capture_u32((unsigned long long)(items_count));
        imgui_wasm_capture_u32((unsigned long long)(height_in_items));
        imgui_wasm_capture_end();
        return ImGui::ListBox(label, current_item, items, items_count, height_in_items);
    }

    inline void LoadIniSettingsFromDisk(const char* ini_filename) {
        imgui_wasm_capture_begin(OP_IG_LOAD_INI_SETTINGS_FROM_DISK);
        imgui_wasm_capture_string(ini_filename);
        imgui_wasm_capture_end();
        ImGui::LoadIniSettingsFromDisk(ini_filename);
    }

    inline void LoadIniSettingsFromMemory(const char* ini_data, unsigned int ini_size = 0) {
        imgui_wasm_capture_begin(OP_IG_LOAD_INI_SETTINGS_FROM_MEMORY);
        imgui_wasm_capture_string(ini_data);
        imgui_wasm_capture_u32((unsigned long long)(ini_size));
        imgui_wasm_capture_end();
        ImGui::LoadIniSettingsFromMemory(ini_data, ini_size);
    }

    inline void LogButtons() {
        imgui_wasm_capture_begin(OP_IG_LOG_BUTTONS);
        imgui_wasm_capture_end();
        ImGui::LogButtons();
    }

    inline void LogFinish() {
        imgui_wasm_capture_begin(OP_IG_LOG_FINISH);
        imgui_wasm_capture_end();
        ImGui::LogFinish();
    }

    inline void LogToClipboard(int auto_open_depth = -1) {
        imgui_wasm_capture_begin(OP_IG_LOG_TO_CLIPBOARD);
        imgui_wasm_capture_u32((unsigned long long)(auto_open_depth));
        imgui_wasm_capture_end();
        ImGui::LogToClipboard(auto_open_depth);
    }

    inline void LogToFile(int auto_open_depth = -1, const char* filename = nullptr) {
        imgui_wasm_capture_begin(OP_IG_LOG_TO_FILE);
        imgui_wasm_capture_u32((unsigned long long)(auto_open_depth));
        imgui_wasm_capture_string(filename);
        imgui_wasm_capture_end();
        ImGui::LogToFile(auto_open_depth, filename);
    }

    inline void LogToTTY(int auto_open_depth = -1) {
        imgui_wasm_capture_begin(OP_IG_LOG_TO_TTY);
        imgui_wasm_capture_u32((unsigned long long)(auto_open_depth));
        imgui_wasm_capture_end();
        ImGui::LogToTTY(auto_open_depth);
    }

    inline void* MemAlloc(unsigned int size) {
        imgui_wasm_capture_begin(OP_IG_MEM_ALLOC);
        imgui_wasm_capture_u32((unsigned long long)(size));
        imgui_wasm_capture_end();
        return ImGui::MemAlloc(size);
    }

    inline bool MenuItem(const char* label, const char* shortcut = nullptr, bool selected = false, bool enabled = true) {
        imgui_wasm_capture_begin(OP_IG_MENU_ITEM);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_string(shortcut);
        imgui_wasm_capture_u8((unsigned long long)(selected));
        imgui_wasm_capture_u8((unsigned long long)(enabled));
        imgui_wasm_capture_end();
        return ImGui::MenuItem(label, shortcut, selected, enabled);
    }

    inline bool MenuItem(const char* label, const char* shortcut, bool* p_selected, bool enabled = true) {
        imgui_wasm_capture_begin(OP_IG_MENU_ITEM_BOOL_PTR);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_string(shortcut);
        imgui_wasm_capture_ptr((const void*)(p_selected), 1u);
        imgui_wasm_capture_u8((unsigned long long)(enabled));
        imgui_wasm_capture_end();
        return ImGui::MenuItem(label, shortcut, p_selected, enabled);
    }

    inline void NewFrame() {
        imgui_wasm_capture_begin(OP_IG_NEW_FRAME);
        imgui_wasm_capture_end();
        ImGui::NewFrame();
    }

    inline void NewLine() {
        imgui_wasm_capture_begin(OP_IG_NEW_LINE);
        imgui_wasm_capture_end();
        ImGui::NewLine();
    }

    inline void NextColumn() {
        imgui_wasm_capture_begin(OP_IG_NEXT_COLUMN);
        imgui_wasm_capture_end();
        ImGui::NextColumn();
    }

    inline void OpenPopupOnItemClick(const char* str_id = nullptr, ImGuiPopupFlags popup_flags = 0) {
        imgui_wasm_capture_begin(OP_IG_OPEN_POPUP_ON_ITEM_CLICK);
        imgui_wasm_capture_string(str_id);
        imgui_wasm_capture_u32((unsigned)(popup_flags));
        imgui_wasm_capture_end();
        ImGui::OpenPopupOnItemClick(str_id, popup_flags);
    }

    inline void OpenPopup(unsigned int id, ImGuiPopupFlags popup_flags = 0) {
        imgui_wasm_capture_begin(OP_IG_OPEN_POPUP_ID);
        imgui_wasm_capture_u32((unsigned long long)(id));
        imgui_wasm_capture_u32((unsigned)(popup_flags));
        imgui_wasm_capture_end();
        ImGui::OpenPopup(id, popup_flags);
    }

    inline void OpenPopup(const char* str_id, ImGuiPopupFlags popup_flags = 0) {
        imgui_wasm_capture_begin(OP_IG_OPEN_POPUP);
        imgui_wasm_capture_string(str_id);
        imgui_wasm_capture_u32((unsigned)(popup_flags));
        imgui_wasm_capture_end();
        ImGui::OpenPopup(str_id, popup_flags);
    }

    inline void PlotHistogram(const char* label, const float* values, int values_count, int values_offset = 0, const char* overlay_text = nullptr, float scale_min = FLT_MAX, float scale_max = FLT_MAX, const ImVec2& graph_size = ImVec2(0, 0), int stride = sizeof(float)) {
        imgui_wasm_capture_begin(OP_IG_PLOT_HISTOGRAM);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_u32((unsigned)(values_count));
        imgui_wasm_capture_floats_n(values, (unsigned)(values_count));
        imgui_wasm_capture_u32((unsigned long long)(values_count));
        imgui_wasm_capture_u32((unsigned long long)(values_offset));
        imgui_wasm_capture_string(overlay_text);
        imgui_wasm_capture_ptr((const void*)(&scale_min), 4u);
        imgui_wasm_capture_ptr((const void*)(&scale_max), 4u);
        imgui_wasm_capture_vec2(graph_size.x, graph_size.y);
        imgui_wasm_capture_u32((unsigned long long)(stride));
        imgui_wasm_capture_end();
        ImGui::PlotHistogram(label, values, values_count, values_offset, overlay_text, scale_min, scale_max, graph_size, stride);
    }

    inline void PlotLines(const char* label, const float* values, int values_count, int values_offset = 0, const char* overlay_text = nullptr, float scale_min = FLT_MAX, float scale_max = FLT_MAX, const ImVec2& graph_size = ImVec2(0, 0), int stride = sizeof(float)) {
        imgui_wasm_capture_begin(OP_IG_PLOT_LINES);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_u32((unsigned)(values_count));
        imgui_wasm_capture_floats_n(values, (unsigned)(values_count));
        imgui_wasm_capture_u32((unsigned long long)(values_count));
        imgui_wasm_capture_u32((unsigned long long)(values_offset));
        imgui_wasm_capture_string(overlay_text);
        imgui_wasm_capture_ptr((const void*)(&scale_min), 4u);
        imgui_wasm_capture_ptr((const void*)(&scale_max), 4u);
        imgui_wasm_capture_vec2(graph_size.x, graph_size.y);
        imgui_wasm_capture_u32((unsigned long long)(stride));
        imgui_wasm_capture_end();
        ImGui::PlotLines(label, values, values_count, values_offset, overlay_text, scale_min, scale_max, graph_size, stride);
    }

    inline void PopClipRect() {
        imgui_wasm_capture_begin(OP_IG_POP_CLIP_RECT);
        imgui_wasm_capture_end();
        ImGui::PopClipRect();
    }

    inline void PopFont() {
        imgui_wasm_capture_begin(OP_IG_POP_FONT);
        imgui_wasm_capture_end();
        ImGui::PopFont();
    }

    inline void PopID() {
        imgui_wasm_capture_begin(OP_IG_POP_ID);
        imgui_wasm_capture_end();
        ImGui::PopID();
    }

    inline void PopItemFlag() {
        imgui_wasm_capture_begin(OP_IG_POP_ITEM_FLAG);
        imgui_wasm_capture_end();
        ImGui::PopItemFlag();
    }

    inline void PopItemWidth() {
        imgui_wasm_capture_begin(OP_IG_POP_ITEM_WIDTH);
        imgui_wasm_capture_end();
        ImGui::PopItemWidth();
    }

    inline void PopStyleColor(int count = 1) {
        imgui_wasm_capture_begin(OP_IG_POP_STYLE_COLOR);
        imgui_wasm_capture_u32((unsigned long long)(count));
        imgui_wasm_capture_end();
        ImGui::PopStyleColor(count);
    }

    inline void PopStyleVar(int count = 1) {
        imgui_wasm_capture_begin(OP_IG_POP_STYLE_VAR);
        imgui_wasm_capture_u32((unsigned long long)(count));
        imgui_wasm_capture_end();
        ImGui::PopStyleVar(count);
    }

    inline void PopTextWrapPos() {
        imgui_wasm_capture_begin(OP_IG_POP_TEXT_WRAP_POS);
        imgui_wasm_capture_end();
        ImGui::PopTextWrapPos();
    }

    inline void ProgressBar(float fraction, const ImVec2& size_arg = ImVec2(-FLT_MIN, 0), const char* overlay = nullptr) {
        imgui_wasm_capture_begin(OP_IG_PROGRESS_BAR);
        imgui_wasm_capture_ptr((const void*)(&fraction), 4u);
        imgui_wasm_capture_vec2(size_arg.x, size_arg.y);
        imgui_wasm_capture_string(overlay);
        imgui_wasm_capture_end();
        ImGui::ProgressBar(fraction, size_arg, overlay);
    }

    inline void PushClipRect(const ImVec2& clip_rect_min, const ImVec2& clip_rect_max, bool intersect_with_current_clip_rect) {
        imgui_wasm_capture_begin(OP_IG_PUSH_CLIP_RECT);
        imgui_wasm_capture_vec2(clip_rect_min.x, clip_rect_min.y);
        imgui_wasm_capture_vec2(clip_rect_max.x, clip_rect_max.y);
        imgui_wasm_capture_u8((unsigned long long)(intersect_with_current_clip_rect));
        imgui_wasm_capture_end();
        ImGui::PushClipRect(clip_rect_min, clip_rect_max, intersect_with_current_clip_rect);
    }

    inline void PushID(int int_id) {
        imgui_wasm_capture_begin(OP_IG_PUSH_ID_INT);
        imgui_wasm_capture_u32((unsigned long long)(int_id));
        imgui_wasm_capture_end();
        ImGui::PushID(int_id);
    }

    inline void PushID(const char* str_id) {
        imgui_wasm_capture_begin(OP_IG_PUSH_ID);
        imgui_wasm_capture_string(str_id);
        imgui_wasm_capture_end();
        ImGui::PushID(str_id);
    }

    inline void PushID(const char* str_id_begin, const char* str_id_end) {
        imgui_wasm_capture_begin(OP_IG_PUSH_ID_STR);
        imgui_wasm_capture_string(str_id_begin);
        imgui_wasm_capture_string(str_id_end);
        imgui_wasm_capture_end();
        ImGui::PushID(str_id_begin, str_id_end);
    }

    inline void PushItemFlag(ImGuiItemFlags option, bool enabled) {
        imgui_wasm_capture_begin(OP_IG_PUSH_ITEM_FLAG);
        imgui_wasm_capture_u32((unsigned)(option));
        imgui_wasm_capture_u8((unsigned long long)(enabled));
        imgui_wasm_capture_end();
        ImGui::PushItemFlag(option, enabled);
    }

    inline void PushItemWidth(float item_width) {
        imgui_wasm_capture_begin(OP_IG_PUSH_ITEM_WIDTH);
        imgui_wasm_capture_ptr((const void*)(&item_width), 4u);
        imgui_wasm_capture_end();
        ImGui::PushItemWidth(item_width);
    }

    inline void PushTextWrapPos(float wrap_local_pos_x = 0.0f) {
        imgui_wasm_capture_begin(OP_IG_PUSH_TEXT_WRAP_POS);
        imgui_wasm_capture_ptr((const void*)(&wrap_local_pos_x), 4u);
        imgui_wasm_capture_end();
        ImGui::PushTextWrapPos(wrap_local_pos_x);
    }

    inline bool RadioButton(const char* label, bool active) {
        imgui_wasm_capture_begin(OP_IG_RADIO_BUTTON);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_u8((unsigned long long)(active));
        imgui_wasm_capture_end();
        return ImGui::RadioButton(label, active);
    }

    inline bool RadioButton(const char* label, int* v, int v_button) {
        imgui_wasm_capture_begin(OP_IG_RADIO_BUTTON_INT_PTR);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_ptr((const void*)(v), 4u);
        imgui_wasm_capture_u32((unsigned long long)(v_button));
        imgui_wasm_capture_end();
        return ImGui::RadioButton(label, v, v_button);
    }

    inline void Render() {
        imgui_wasm_capture_begin(OP_IG_RENDER);
        imgui_wasm_capture_end();
        ImGui::Render();
    }

    inline void ResetMouseDragDelta(ImGuiMouseButton button = 0) {
        imgui_wasm_capture_begin(OP_IG_RESET_MOUSE_DRAG_DELTA);
        imgui_wasm_capture_u32((unsigned)(button));
        imgui_wasm_capture_end();
        ImGui::ResetMouseDragDelta(button);
    }

    inline void SameLine(float offset_from_start_x = 0.0f, float spacing = -1.0f) {
        imgui_wasm_capture_begin(OP_IG_SAME_LINE);
        imgui_wasm_capture_ptr((const void*)(&offset_from_start_x), 4u);
        imgui_wasm_capture_ptr((const void*)(&spacing), 4u);
        imgui_wasm_capture_end();
        ImGui::SameLine(offset_from_start_x, spacing);
    }

    inline void SaveIniSettingsToDisk(const char* ini_filename) {
        imgui_wasm_capture_begin(OP_IG_SAVE_INI_SETTINGS_TO_DISK);
        imgui_wasm_capture_string(ini_filename);
        imgui_wasm_capture_end();
        ImGui::SaveIniSettingsToDisk(ini_filename);
    }

    inline const char* SaveIniSettingsToMemory(size_t* out_ini_size = nullptr) {
        imgui_wasm_capture_begin(OP_IG_SAVE_INI_SETTINGS_TO_MEMORY);
        imgui_wasm_capture_ptr((const void*)(out_ini_size), 4u);
        imgui_wasm_capture_end();
        return ImGui::SaveIniSettingsToMemory(out_ini_size);
    }

    inline bool Selectable(const char* label, bool selected = false, ImGuiSelectableFlags flags = 0, const ImVec2& size = ImVec2(0, 0)) {
        imgui_wasm_capture_begin(OP_IG_SELECTABLE);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_u8((unsigned long long)(selected));
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_vec2(size.x, size.y);
        imgui_wasm_capture_end();
        return ImGui::Selectable(label, selected, flags, size);
    }

    inline bool Selectable(const char* label, bool* p_selected, ImGuiSelectableFlags flags = 0, const ImVec2& size = ImVec2(0, 0)) {
        imgui_wasm_capture_begin(OP_IG_SELECTABLE_BOOL_PTR);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_ptr((const void*)(p_selected), 1u);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_vec2(size.x, size.y);
        imgui_wasm_capture_end();
        return ImGui::Selectable(label, p_selected, flags, size);
    }

    inline void Separator() {
        imgui_wasm_capture_begin(OP_IG_SEPARATOR);
        imgui_wasm_capture_end();
        ImGui::Separator();
    }

    inline void SeparatorText(const char* label) {
        imgui_wasm_capture_begin(OP_IG_SEPARATOR_TEXT);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_end();
        ImGui::SeparatorText(label);
    }

    inline void SetClipboardText(const char* text) {
        imgui_wasm_capture_begin(OP_IG_SET_CLIPBOARD_TEXT);
        imgui_wasm_capture_string(text);
        imgui_wasm_capture_end();
        ImGui::SetClipboardText(text);
    }

    inline void SetColorEditOptions(ImGuiColorEditFlags flags) {
        imgui_wasm_capture_begin(OP_IG_SET_COLOR_EDIT_OPTIONS);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        ImGui::SetColorEditOptions(flags);
    }

    inline void SetColumnOffset(int column_index, float offset_x) {
        imgui_wasm_capture_begin(OP_IG_SET_COLUMN_OFFSET);
        imgui_wasm_capture_u32((unsigned long long)(column_index));
        imgui_wasm_capture_ptr((const void*)(&offset_x), 4u);
        imgui_wasm_capture_end();
        ImGui::SetColumnOffset(column_index, offset_x);
    }

    inline void SetColumnWidth(int column_index, float width) {
        imgui_wasm_capture_begin(OP_IG_SET_COLUMN_WIDTH);
        imgui_wasm_capture_u32((unsigned long long)(column_index));
        imgui_wasm_capture_ptr((const void*)(&width), 4u);
        imgui_wasm_capture_end();
        ImGui::SetColumnWidth(column_index, width);
    }

    inline void SetCursorPos(const ImVec2& local_pos) {
        imgui_wasm_capture_begin(OP_IG_SET_CURSOR_POS);
        imgui_wasm_capture_vec2(local_pos.x, local_pos.y);
        imgui_wasm_capture_end();
        ImGui::SetCursorPos(local_pos);
    }

    inline void SetCursorPosX(float local_x) {
        imgui_wasm_capture_begin(OP_IG_SET_CURSOR_POS_X);
        imgui_wasm_capture_ptr((const void*)(&local_x), 4u);
        imgui_wasm_capture_end();
        ImGui::SetCursorPosX(local_x);
    }

    inline void SetCursorPosY(float local_y) {
        imgui_wasm_capture_begin(OP_IG_SET_CURSOR_POS_Y);
        imgui_wasm_capture_ptr((const void*)(&local_y), 4u);
        imgui_wasm_capture_end();
        ImGui::SetCursorPosY(local_y);
    }

    inline void SetCursorScreenPos(const ImVec2& pos) {
        imgui_wasm_capture_begin(OP_IG_SET_CURSOR_SCREEN_POS);
        imgui_wasm_capture_vec2(pos.x, pos.y);
        imgui_wasm_capture_end();
        ImGui::SetCursorScreenPos(pos);
    }

    inline void SetItemDefaultFocus() {
        imgui_wasm_capture_begin(OP_IG_SET_ITEM_DEFAULT_FOCUS);
        imgui_wasm_capture_end();
        ImGui::SetItemDefaultFocus();
    }

    inline bool SetItemKeyOwner(ImGuiKey key) {
        imgui_wasm_capture_begin(OP_IG_SET_ITEM_KEY_OWNER);
        imgui_wasm_capture_u32((unsigned)(key));
        imgui_wasm_capture_end();
        return ImGui::SetItemKeyOwner(key);
    }

    inline void SetKeyboardFocusHere(int offset = 0) {
        imgui_wasm_capture_begin(OP_IG_SET_KEYBOARD_FOCUS_HERE);
        imgui_wasm_capture_u32((unsigned long long)(offset));
        imgui_wasm_capture_end();
        ImGui::SetKeyboardFocusHere(offset);
    }

    inline void SetMouseCursor(ImGuiMouseCursor cursor_type) {
        imgui_wasm_capture_begin(OP_IG_SET_MOUSE_CURSOR);
        imgui_wasm_capture_u32((unsigned)(cursor_type));
        imgui_wasm_capture_end();
        ImGui::SetMouseCursor(cursor_type);
    }

    inline void SetNavCursorVisible(bool visible) {
        imgui_wasm_capture_begin(OP_IG_SET_NAV_CURSOR_VISIBLE);
        imgui_wasm_capture_u8((unsigned long long)(visible));
        imgui_wasm_capture_end();
        ImGui::SetNavCursorVisible(visible);
    }

    inline void SetNextFrameWantCaptureKeyboard(bool want_capture_keyboard) {
        imgui_wasm_capture_begin(OP_IG_SET_NEXT_FRAME_WANT_CAPTURE_KEYBOARD);
        imgui_wasm_capture_u8((unsigned long long)(want_capture_keyboard));
        imgui_wasm_capture_end();
        ImGui::SetNextFrameWantCaptureKeyboard(want_capture_keyboard);
    }

    inline void SetNextFrameWantCaptureMouse(bool want_capture_mouse) {
        imgui_wasm_capture_begin(OP_IG_SET_NEXT_FRAME_WANT_CAPTURE_MOUSE);
        imgui_wasm_capture_u8((unsigned long long)(want_capture_mouse));
        imgui_wasm_capture_end();
        ImGui::SetNextFrameWantCaptureMouse(want_capture_mouse);
    }

    inline void SetNextItemAllowOverlap() {
        imgui_wasm_capture_begin(OP_IG_SET_NEXT_ITEM_ALLOW_OVERLAP);
        imgui_wasm_capture_end();
        ImGui::SetNextItemAllowOverlap();
    }

    inline void SetNextItemStorageID(unsigned int storage_id) {
        imgui_wasm_capture_begin(OP_IG_SET_NEXT_ITEM_STORAGE_ID);
        imgui_wasm_capture_u32((unsigned long long)(storage_id));
        imgui_wasm_capture_end();
        ImGui::SetNextItemStorageID(storage_id);
    }

    inline void SetNextItemWidth(float item_width) {
        imgui_wasm_capture_begin(OP_IG_SET_NEXT_ITEM_WIDTH);
        imgui_wasm_capture_ptr((const void*)(&item_width), 4u);
        imgui_wasm_capture_end();
        ImGui::SetNextItemWidth(item_width);
    }

    inline void SetNextWindowBgAlpha(float alpha) {
        imgui_wasm_capture_begin(OP_IG_SET_NEXT_WINDOW_BG_ALPHA);
        imgui_wasm_capture_ptr((const void*)(&alpha), 4u);
        imgui_wasm_capture_end();
        ImGui::SetNextWindowBgAlpha(alpha);
    }

    inline void SetNextWindowContentSize(const ImVec2& size) {
        imgui_wasm_capture_begin(OP_IG_SET_NEXT_WINDOW_CONTENT_SIZE);
        imgui_wasm_capture_vec2(size.x, size.y);
        imgui_wasm_capture_end();
        ImGui::SetNextWindowContentSize(size);
    }

    inline void SetNextWindowFocus() {
        imgui_wasm_capture_begin(OP_IG_SET_NEXT_WINDOW_FOCUS);
        imgui_wasm_capture_end();
        ImGui::SetNextWindowFocus();
    }

    inline void SetNextWindowScroll(const ImVec2& scroll) {
        imgui_wasm_capture_begin(OP_IG_SET_NEXT_WINDOW_SCROLL);
        imgui_wasm_capture_vec2(scroll.x, scroll.y);
        imgui_wasm_capture_end();
        ImGui::SetNextWindowScroll(scroll);
    }

    inline void SetNextWindowViewport(unsigned int viewport_id) {
        imgui_wasm_capture_begin(OP_IG_SET_NEXT_WINDOW_VIEWPORT);
        imgui_wasm_capture_u32((unsigned long long)(viewport_id));
        imgui_wasm_capture_end();
        ImGui::SetNextWindowViewport(viewport_id);
    }

    inline void SetScrollFromPosX(float local_x, float center_x_ratio = 0.5f) {
        imgui_wasm_capture_begin(OP_IG_SET_SCROLL_FROM_POS_X);
        imgui_wasm_capture_ptr((const void*)(&local_x), 4u);
        imgui_wasm_capture_ptr((const void*)(&center_x_ratio), 4u);
        imgui_wasm_capture_end();
        ImGui::SetScrollFromPosX(local_x, center_x_ratio);
    }

    inline void SetScrollFromPosY(float local_y, float center_y_ratio = 0.5f) {
        imgui_wasm_capture_begin(OP_IG_SET_SCROLL_FROM_POS_Y);
        imgui_wasm_capture_ptr((const void*)(&local_y), 4u);
        imgui_wasm_capture_ptr((const void*)(&center_y_ratio), 4u);
        imgui_wasm_capture_end();
        ImGui::SetScrollFromPosY(local_y, center_y_ratio);
    }

    inline void SetScrollHereX(float center_x_ratio = 0.5f) {
        imgui_wasm_capture_begin(OP_IG_SET_SCROLL_HERE_X);
        imgui_wasm_capture_ptr((const void*)(&center_x_ratio), 4u);
        imgui_wasm_capture_end();
        ImGui::SetScrollHereX(center_x_ratio);
    }

    inline void SetScrollHereY(float center_y_ratio = 0.5f) {
        imgui_wasm_capture_begin(OP_IG_SET_SCROLL_HERE_Y);
        imgui_wasm_capture_ptr((const void*)(&center_y_ratio), 4u);
        imgui_wasm_capture_end();
        ImGui::SetScrollHereY(center_y_ratio);
    }

    inline void SetScrollX(float scroll_x) {
        imgui_wasm_capture_begin(OP_IG_SET_SCROLL_X);
        imgui_wasm_capture_ptr((const void*)(&scroll_x), 4u);
        imgui_wasm_capture_end();
        ImGui::SetScrollX(scroll_x);
    }

    inline void SetScrollY(float scroll_y) {
        imgui_wasm_capture_begin(OP_IG_SET_SCROLL_Y);
        imgui_wasm_capture_ptr((const void*)(&scroll_y), 4u);
        imgui_wasm_capture_end();
        ImGui::SetScrollY(scroll_y);
    }

    inline void SetTabItemClosed(const char* tab_or_docked_window_label) {
        imgui_wasm_capture_begin(OP_IG_SET_TAB_ITEM_CLOSED);
        imgui_wasm_capture_string(tab_or_docked_window_label);
        imgui_wasm_capture_end();
        ImGui::SetTabItemClosed(tab_or_docked_window_label);
    }

    inline void SetWindowFocus() {
        imgui_wasm_capture_begin(OP_IG_SET_WINDOW_FOCUS);
        imgui_wasm_capture_end();
        ImGui::SetWindowFocus();
    }

    inline void SetWindowFocus(const char* name) {
        imgui_wasm_capture_begin(OP_IG_SET_WINDOW_FOCUS_STR);
        imgui_wasm_capture_string(name);
        imgui_wasm_capture_end();
        ImGui::SetWindowFocus(name);
    }

    inline void ShowAboutWindow(bool* p_open = nullptr) {
        imgui_wasm_capture_begin(OP_IG_SHOW_ABOUT_WINDOW);
        imgui_wasm_capture_ptr((const void*)(p_open), 1u);
        imgui_wasm_capture_end();
        ImGui::ShowAboutWindow(p_open);
    }

    inline void ShowDebugLogWindow(bool* p_open = nullptr) {
        imgui_wasm_capture_begin(OP_IG_SHOW_DEBUG_LOG_WINDOW);
        imgui_wasm_capture_ptr((const void*)(p_open), 1u);
        imgui_wasm_capture_end();
        ImGui::ShowDebugLogWindow(p_open);
    }

    inline void ShowDemoWindow(bool* p_open = nullptr) {
        imgui_wasm_capture_begin(OP_IG_SHOW_DEMO_WINDOW);
        imgui_wasm_capture_ptr((const void*)(p_open), 1u);
        imgui_wasm_capture_end();
        ImGui::ShowDemoWindow(p_open);
    }

    inline void ShowFontSelector(const char* label) {
        imgui_wasm_capture_begin(OP_IG_SHOW_FONT_SELECTOR);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_end();
        ImGui::ShowFontSelector(label);
    }

    inline void ShowIDStackToolWindow(bool* p_open = nullptr) {
        imgui_wasm_capture_begin(OP_IG_SHOW_ID_STACK_TOOL_WINDOW);
        imgui_wasm_capture_ptr((const void*)(p_open), 1u);
        imgui_wasm_capture_end();
        ImGui::ShowIDStackToolWindow(p_open);
    }

    inline void ShowMetricsWindow(bool* p_open = nullptr) {
        imgui_wasm_capture_begin(OP_IG_SHOW_METRICS_WINDOW);
        imgui_wasm_capture_ptr((const void*)(p_open), 1u);
        imgui_wasm_capture_end();
        ImGui::ShowMetricsWindow(p_open);
    }

    inline bool ShowStyleSelector(const char* label) {
        imgui_wasm_capture_begin(OP_IG_SHOW_STYLE_SELECTOR);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_end();
        return ImGui::ShowStyleSelector(label);
    }

    inline void ShowUserGuide() {
        imgui_wasm_capture_begin(OP_IG_SHOW_USER_GUIDE);
        imgui_wasm_capture_end();
        ImGui::ShowUserGuide();
    }

    inline bool SliderAngle(const char* label, float* v_rad, float v_degrees_min = -360.0f, float v_degrees_max = +360.0f, const char* format = "%.0f deg", ImGuiSliderFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_SLIDER_ANGLE);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_ptr((const void*)(v_rad), 4u);
        imgui_wasm_capture_ptr((const void*)(&v_degrees_min), 4u);
        imgui_wasm_capture_ptr((const void*)(&v_degrees_max), 4u);
        imgui_wasm_capture_string(format);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::SliderAngle(label, v_rad, v_degrees_min, v_degrees_max, format, flags);
    }

    inline bool SliderFloat(const char* label, float* v, float v_min, float v_max, const char* format = "%.3f", ImGuiSliderFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_SLIDER_FLOAT);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_ptr((const void*)(v), 4u);
        imgui_wasm_capture_ptr((const void*)(&v_min), 4u);
        imgui_wasm_capture_ptr((const void*)(&v_max), 4u);
        imgui_wasm_capture_string(format);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::SliderFloat(label, v, v_min, v_max, format, flags);
    }

    inline bool SliderFloat3(const char* label, float* v, float v_min, float v_max, const char* format = "%.3f", ImGuiSliderFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_SLIDER_FLOAT_3);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_floats(v, 3);
        imgui_wasm_capture_ptr((const void*)(&v_min), 4u);
        imgui_wasm_capture_ptr((const void*)(&v_max), 4u);
        imgui_wasm_capture_string(format);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::SliderFloat3(label, v, v_min, v_max, format, flags);
    }

    inline bool SliderFloat4(const char* label, float* v, float v_min, float v_max, const char* format = "%.3f", ImGuiSliderFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_SLIDER_FLOAT_4);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_floats(v, 4);
        imgui_wasm_capture_ptr((const void*)(&v_min), 4u);
        imgui_wasm_capture_ptr((const void*)(&v_max), 4u);
        imgui_wasm_capture_string(format);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::SliderFloat4(label, v, v_min, v_max, format, flags);
    }

    inline bool SliderInt(const char* label, int* v, int v_min, int v_max, const char* format = "%d", ImGuiSliderFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_SLIDER_INT);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_ptr((const void*)(v), 4u);
        imgui_wasm_capture_u32((unsigned long long)(v_min));
        imgui_wasm_capture_u32((unsigned long long)(v_max));
        imgui_wasm_capture_string(format);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::SliderInt(label, v, v_min, v_max, format, flags);
    }

    inline bool SmallButton(const char* label) {
        imgui_wasm_capture_begin(OP_IG_SMALL_BUTTON);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_end();
        return ImGui::SmallButton(label);
    }

    inline void Spacing() {
        imgui_wasm_capture_begin(OP_IG_SPACING);
        imgui_wasm_capture_end();
        ImGui::Spacing();
    }

    inline bool TabItemButton(const char* label, ImGuiTabItemFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_TAB_ITEM_BUTTON);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::TabItemButton(label, flags);
    }

    inline void TableAngledHeadersRow() {
        imgui_wasm_capture_begin(OP_IG_TABLE_ANGLED_HEADERS_ROW);
        imgui_wasm_capture_end();
        ImGui::TableAngledHeadersRow();
    }

    inline int TableGetColumnCount() {
        imgui_wasm_capture_begin(OP_IG_TABLE_GET_COLUMN_COUNT);
        imgui_wasm_capture_end();
        return ImGui::TableGetColumnCount();
    }

    inline ImGuiTableColumnFlags TableGetColumnFlags(int column_n = -1) {
        imgui_wasm_capture_begin(OP_IG_TABLE_GET_COLUMN_FLAGS);
        imgui_wasm_capture_u32((unsigned long long)(column_n));
        imgui_wasm_capture_end();
        return ImGui::TableGetColumnFlags(column_n);
    }

    inline int TableGetColumnIndex() {
        imgui_wasm_capture_begin(OP_IG_TABLE_GET_COLUMN_INDEX);
        imgui_wasm_capture_end();
        return ImGui::TableGetColumnIndex();
    }

    inline const char* TableGetColumnName(int column_n = -1) {
        imgui_wasm_capture_begin(OP_IG_TABLE_GET_COLUMN_NAME);
        imgui_wasm_capture_u32((unsigned long long)(column_n));
        imgui_wasm_capture_end();
        return ImGui::TableGetColumnName(column_n);
    }

    inline int TableGetHoveredColumn() {
        imgui_wasm_capture_begin(OP_IG_TABLE_GET_HOVERED_COLUMN);
        imgui_wasm_capture_end();
        return ImGui::TableGetHoveredColumn();
    }

    inline int TableGetRowIndex() {
        imgui_wasm_capture_begin(OP_IG_TABLE_GET_ROW_INDEX);
        imgui_wasm_capture_end();
        return ImGui::TableGetRowIndex();
    }

    inline ImGuiTableSortSpecs* TableGetSortSpecs() {
        imgui_wasm_capture_begin(OP_IG_TABLE_GET_SORT_SPECS);
        imgui_wasm_capture_end();
        return ImGui::TableGetSortSpecs();
    }

    inline void TableHeader(const char* label) {
        imgui_wasm_capture_begin(OP_IG_TABLE_HEADER);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_end();
        ImGui::TableHeader(label);
    }

    inline void TableHeadersRow() {
        imgui_wasm_capture_begin(OP_IG_TABLE_HEADERS_ROW);
        imgui_wasm_capture_end();
        ImGui::TableHeadersRow();
    }

    inline bool TableNextColumn() {
        imgui_wasm_capture_begin(OP_IG_TABLE_NEXT_COLUMN);
        imgui_wasm_capture_end();
        return ImGui::TableNextColumn();
    }

    inline void TableNextRow(ImGuiTableRowFlags row_flags = 0, float min_row_height = 0.0f) {
        imgui_wasm_capture_begin(OP_IG_TABLE_NEXT_ROW);
        imgui_wasm_capture_u32((unsigned)(row_flags));
        imgui_wasm_capture_ptr((const void*)(&min_row_height), 4u);
        imgui_wasm_capture_end();
        ImGui::TableNextRow(row_flags, min_row_height);
    }

    inline void TableSetColumnEnabled(int column_n, bool v) {
        imgui_wasm_capture_begin(OP_IG_TABLE_SET_COLUMN_ENABLED);
        imgui_wasm_capture_u32((unsigned long long)(column_n));
        imgui_wasm_capture_u8((unsigned long long)(v));
        imgui_wasm_capture_end();
        ImGui::TableSetColumnEnabled(column_n, v);
    }

    inline bool TableSetColumnIndex(int column_n) {
        imgui_wasm_capture_begin(OP_IG_TABLE_SET_COLUMN_INDEX);
        imgui_wasm_capture_u32((unsigned long long)(column_n));
        imgui_wasm_capture_end();
        return ImGui::TableSetColumnIndex(column_n);
    }

    inline void TableSetupColumn(const char* label, ImGuiTableColumnFlags flags = 0, float init_width_or_weight = 0.0f, unsigned int user_id = 0) {
        imgui_wasm_capture_begin(OP_IG_TABLE_SETUP_COLUMN);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_ptr((const void*)(&init_width_or_weight), 4u);
        imgui_wasm_capture_u32((unsigned long long)(user_id));
        imgui_wasm_capture_end();
        ImGui::TableSetupColumn(label, flags, init_width_or_weight, user_id);
    }

    inline void TableSetupScrollFreeze(int cols, int rows) {
        imgui_wasm_capture_begin(OP_IG_TABLE_SETUP_SCROLL_FREEZE);
        imgui_wasm_capture_u32((unsigned long long)(cols));
        imgui_wasm_capture_u32((unsigned long long)(rows));
        imgui_wasm_capture_end();
        ImGui::TableSetupScrollFreeze(cols, rows);
    }

    inline bool TextLink(const char* label) {
        imgui_wasm_capture_begin(OP_IG_TEXT_LINK);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_end();
        return ImGui::TextLink(label);
    }

    inline bool TextLinkOpenURL(const char* label, const char* url = nullptr) {
        imgui_wasm_capture_begin(OP_IG_TEXT_LINK_OPEN_URL);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_string(url);
        imgui_wasm_capture_end();
        return ImGui::TextLinkOpenURL(label, url);
    }

    inline void TextUnformatted(const char* text, const char* text_end = nullptr) {
        imgui_wasm_capture_begin(OP_IG_TEXT_UNFORMATTED);
        imgui_wasm_capture_string(text);
        imgui_wasm_capture_string(text_end);
        imgui_wasm_capture_end();
        ImGui::TextUnformatted(text, text_end);
    }

    inline bool TreeNodeEx(const char* label, ImGuiTreeNodeFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_TREE_NODE_EX);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::TreeNodeEx(label, flags);
    }

    inline bool TreeNodeGetOpen(unsigned int storage_id) {
        imgui_wasm_capture_begin(OP_IG_TREE_NODE_GET_OPEN);
        imgui_wasm_capture_u32((unsigned long long)(storage_id));
        imgui_wasm_capture_end();
        return ImGui::TreeNodeGetOpen(storage_id);
    }

    inline bool TreeNode(const char* label) {
        imgui_wasm_capture_begin(OP_IG_TREE_NODE);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_end();
        return ImGui::TreeNode(label);
    }

    inline void TreePop() {
        imgui_wasm_capture_begin(OP_IG_TREE_POP);
        imgui_wasm_capture_end();
        ImGui::TreePop();
    }

    inline void TreePush(const char* str_id) {
        imgui_wasm_capture_begin(OP_IG_TREE_PUSH);
        imgui_wasm_capture_string(str_id);
        imgui_wasm_capture_end();
        ImGui::TreePush(str_id);
    }

    inline void Unindent(float indent_w = 0.0f) {
        imgui_wasm_capture_begin(OP_IG_UNINDENT);
        imgui_wasm_capture_ptr((const void*)(&indent_w), 4u);
        imgui_wasm_capture_end();
        ImGui::Unindent(indent_w);
    }

    inline void UpdatePlatformWindows() {
        imgui_wasm_capture_begin(OP_IG_UPDATE_PLATFORM_WINDOWS);
        imgui_wasm_capture_end();
        ImGui::UpdatePlatformWindows();
    }

    inline bool VSliderFloat(const char* label, const ImVec2& size, float* v, float v_min, float v_max, const char* format = "%.3f", ImGuiSliderFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_V_SLIDER_FLOAT);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_vec2(size.x, size.y);
        imgui_wasm_capture_ptr((const void*)(v), 4u);
        imgui_wasm_capture_ptr((const void*)(&v_min), 4u);
        imgui_wasm_capture_ptr((const void*)(&v_max), 4u);
        imgui_wasm_capture_string(format);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::VSliderFloat(label, size, v, v_min, v_max, format, flags);
    }

    inline bool VSliderInt(const char* label, const ImVec2& size, int* v, int v_min, int v_max, const char* format = "%d", ImGuiSliderFlags flags = 0) {
        imgui_wasm_capture_begin(OP_IG_V_SLIDER_INT);
        imgui_wasm_capture_string(label);
        imgui_wasm_capture_vec2(size.x, size.y);
        imgui_wasm_capture_ptr((const void*)(v), 4u);
        imgui_wasm_capture_u32((unsigned long long)(v_min));
        imgui_wasm_capture_u32((unsigned long long)(v_max));
        imgui_wasm_capture_string(format);
        imgui_wasm_capture_u32((unsigned)(flags));
        imgui_wasm_capture_end();
        return ImGui::VSliderInt(label, size, v, v_min, v_max, format, flags);
    }

} // namespace imgui_wasm

#ifndef IMGUI_WASM_NO_IMGUI_REDIRECT
#define ImGui imgui_wasm
#endif
