#!/usr/bin/env python3
"""Embed frontend assets into a generated C++ source file.

Usage: embed_assets.py OUTPUT.cpp URL_PATH|MIME|FILE [URL_PATH|MIME|FILE...]

Consumed by the CMake build; the generated file defines
imgui_wasm_core::kEmbeddedAssets.
"""

import sys
from pathlib import Path

# Short mime keys keep the CMake COMMAND line free of semicolons (CMake
# expands them as list separators inside quoted arguments).
MIME_TYPES = {
    "html": "text/html; charset=utf-8",
    "css": "text/css; charset=utf-8",
    "js": "application/javascript; charset=utf-8",
    "wasm": "application/wasm",
}


def c_name(url_path: str) -> str:
    return "asset_" + "".join(c if c.isalnum() else "_" for c in url_path)


def main() -> int:
    if len(sys.argv) < 3:
        print(__doc__, file=sys.stderr)
        return 2

    out_path = Path(sys.argv[1])
    entries = []
    for arg in sys.argv[2:]:
        url_path, mime_key, file = arg.split("|", 2)
        if mime_key not in MIME_TYPES:
            print(f"embed_assets: unknown mime key '{mime_key}'", file=sys.stderr)
            return 1
        entries.append((url_path, MIME_TYPES[mime_key], Path(file)))

    for _, _, file in entries:
        if not file.is_file():
            print(f"embed_assets: missing input file {file}", file=sys.stderr)
            return 1

    lines = [
        "// Generated by tools/embed_assets.py — do not edit.",
        "#include <cstddef>",
        "",
        '#include "core.hpp"',
        "",
        "namespace imgui_wasm_core {",
        "namespace {",
    ]
    for url_path, _, file in entries:
        data = file.read_bytes()
        lines.append(f"// {url_path} <- {file}")
        lines.append(f"const unsigned char {c_name(url_path)}[] = {{")
        for i in range(0, len(data), 20):
            chunk = data[i : i + 20]
            lines.append("    " + ",".join(str(b) for b in chunk) + ",")
        lines.append("};")
        lines.append("")
    lines.append("}  // namespace")
    lines.append("")
    lines.append("const Asset kEmbeddedAssets[] = {")
    for url_path, mime, _ in entries:
        lines.append(
            f'    {{"{url_path}", "{mime}", {c_name(url_path)}, sizeof({c_name(url_path)})}},'
        )
    lines.append("};")
    lines.append("const size_t kEmbeddedAssetCount = sizeof(kEmbeddedAssets) / sizeof(kEmbeddedAssets[0]);")
    lines.append("")
    lines.append("}  // namespace imgui_wasm_core")
    lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
